import 'package:flutter/material.dart';

/// Centralized bilingual string management for ShoeStock ERP.
/// Usage: S.t('key') for static access, S.of(context, 'key') with BuildContext.
class S {
  static String _locale = 'ar';

  static void setLocale(String lang) {
    _locale = lang;
  }

  static String get currentLocale => _locale;

  /// Context-aware lookup (same result as t(), provided for API symmetry).
  static String of(BuildContext context, String key) => t(key);

  /// Static lookup — safe in initState, build, async callbacks.
  static String t(String key) => _strings[_locale]?[key] ?? '[$key]';

  // ══════════════════════════════════════════════════════════════
  // Translation maps
  // ══════════════════════════════════════════════════════════════

  static const Map<String, Map<String, String>> _strings = {
    // ────────────────────────────────────────────────────────────
    // FRENCH
    // ────────────────────────────────────────────────────────────
    'fr': {
      // ── Navigation ──
      'nav_dashboard': 'Tableau de Bord',
      'nav_products': 'Produits',
      'nav_add_product': 'Ajouter Produit',
      'nav_inventory': 'Inventaire',
      'nav_sales': 'Historique Ventes',
      'nav_clients': 'Clients',
      'nav_suppliers': 'Fournisseurs',
      'nav_employees': 'Employés',
      'nav_stores': 'Magasins',
      'nav_pos': 'Point de Vente',
      'nav_shifts': 'Gestion Caisse',
      'nav_activity': "Journaux d'activité",
      'nav_expenses': 'Dépenses',
      'nav_recovery': 'Recouvrement',
      'nav_settings': 'Paramètres',
      'nav_purchases': 'Achats Fournisseur',

      // ── Common actions ──
      'action_save': 'Enregistrer',
      'action_cancel': 'Annuler',
      'action_delete': 'Supprimer',
      'action_confirm': 'Confirmer',
      'action_close': 'Fermer',
      'action_refresh': 'Actualiser',
      'action_add': 'Ajouter',
      'action_edit': 'Modifier',
      'action_archive': 'Archiver',
      'action_search': 'Rechercher',
      'action_filter': 'Filtrer',
      'action_print': 'Imprimer',
      'action_export': 'Exporter',
      'action_restore': 'Restaurer',

      // ── Common labels ──
      'label_name': 'Nom',
      'label_phone': 'Téléphone',
      'label_email': 'Adresse e-mail',
      'label_address': 'Adresse',
      'label_amount': 'Montant',
      'label_date': 'Date',
      'label_notes': 'Notes',
      'label_status': 'Statut',
      'label_store': 'Magasin',
      'label_balance': 'Solde',
      'label_total': 'Total',
      'label_quantity': 'Quantité',
      'label_price': 'Prix',
      'label_description': 'Description',
      'label_category': 'Catégorie',
      'label_method': 'Méthode de paiement',
      'label_cash': 'Espèces',
      'label_bank': 'Virement bancaire',
      'label_mobile': 'Mobile',
      'label_active': 'Actif',
      'label_archived': 'Archivé',
      'label_all': 'Tous',
      'label_role': 'Rôle',
      'label_role_admin': 'Administrateur',
      'label_password': 'Mot de passe',
      'label_supplier': 'Fournisseur',
      'label_product': 'Produit',

      // ── Auth ──
      'auth_title': 'Connexion',
      'auth_email': 'Adresse e-mail',
      'auth_password': 'Mot de passe',
      'auth_login': 'Se connecter',
      'auth_logout': 'Déconnexion',
      'auth_error_invalid': 'E-mail ou mot de passe incorrect.',
      'auth_connecting': 'Connexion en cours...',
      'auth_welcome': 'Bienvenue',
      'auth_subtitle': 'Système de gestion de stock',
      'auth_forgot_password': 'Mot de passe oublié ?',
      'auth_access_denied_mobile': 'Accès refusé : Mobile réservé au Propriétaire.',
      'auth_profile_not_found': "Profil utilisateur introuvable. Contactez l'administrateur.",
      'auth_connection_error': 'Erreur de connexion : Impossible de vérifier le profil. Veuillez vérifier votre internet.',
      'auth_fill_fields': 'Veuillez remplir tous les champs.',
      'auth_error_generic': "Une erreur inattendue s'est produite.",
      'auth_welcome_msg': 'Bienvenue, connectez-vous pour continuer',
      'auth_no_account': "Vous n'avez pas de compte ? ",
      'auth_register_here': 'Inscrivez-vous ici',

      // ── POS ──
      'pos_title': 'Point de Vente (POS)',
      'pos_search_hint': 'Rechercher un produit ou scanner un code-barres...',
      'pos_new_sale': 'Nouvelle Vente',
      'pos_today_invoices': 'Factures du Jour',
      'pos_checkout': 'Encaissement',
      'pos_validate_sale': 'Valider la Vente',
      'pos_cart_empty': 'Votre panier est vide',
      'pos_add_to_cart': 'Ajouter au panier',
      'pos_total': 'Total à payer :',
      'pos_paid': 'Montant encaissé (DA)',
      'pos_remaining': 'Reste',
      'pos_sale_success': 'Vente enregistrée ! Facture et stocks mis à jour.',
      'pos_walk_in_customer': 'Client Comptoir',
      'pos_scanner_active': 'Scan actif',
      'pos_no_shift_warning': 'Aucune caisse ouverte',
      'pos_client_optional': 'Client (Optionnel)',
      'pos_debt_note': 'Le reste sera ajouté aux dettes (crédit) du client.',
      'pos_walk_in_note': 'Client Comptoir : Le paiement complet est exigé (Pas de crédit possible).',
      'pos_enter_valid_price': 'Veuillez saisir un prix unitaire valide pour chaque article.',
      'pos_select_store': 'Veuillez sélectionner un magasin.',
      'pos_stock_empty': 'Attention: Stock épuisé pour ce magasin.',
      'pos_no_product': 'Aucun produit trouvé',
      'pos_invoice': 'Facture',
      'pos_client': 'Client',
      'pos_time': 'Heure',
      'pos_credit': 'Crédit (Non soldé)',
      'pos_paid_status': 'Payé',
      'pos_no_invoice_today': "Aucune facture enregistrée aujourd'hui.",
      'pos_store_not_selected': 'Magasin non sélectionné',
      'pos_report': 'Rapport',
      'pos_size': 'Taille',
      'pos_color': 'Couleur',
      'pos_code': 'Code',
      'pos_payment_notes': 'Paiement à la caisse pour facture',
      'pos_unit_price': 'Prix unitaire',
      'pos_system_error': 'Erreur système',
      'pos_cart_title': 'Panier',
      'pos_items': 'articles',

      // ── Shifts ──
      'shift_open_title': 'Ouverture de caisse',
      'shift_close_title': 'Clôturer la caisse',
      'shift_opening_amount': 'Montant initial (DA)',
      'shift_closing_amount': 'Montant réel en caisse',
      'shift_actual_amount': 'Montant réel en caisse',
      'shift_report_title': 'Rapport du jour',
      'shift_surplus': 'Surplus',
      'shift_shortage': 'Déficit',
      'shift_no_shift': 'Jour sans caisse',
      'shift_open_success': 'Caisse ouverte avec succès',
      'shift_close_success': 'Caisse clôturée avec succès',
      'shift_previous_unclosed': "Caisse non clôturée",
      'shift_previous_unclosed_msg': "Une caisse du {date} n'a pas été clôturée.",
      'shift_ignore': 'Ignorer',
      'shift_close_old': "Clôturer l'ancienne",
      'shift_skip': 'Sans caisse',
      'shift_open': 'Ouvrir la caisse',
      'shift_enter_amount': 'Veuillez entrer le montant',
      'shift_invalid_amount': 'Montant invalide',
      'shift_open_error': "Erreur d'ouverture de caisse",
      'shift_retrieve_error': 'Erreur de récupération de la caisse',
      'shift_instructions': "Entrez le montant initial en caisse pour aujourd'hui",
      'shift_initial_amount': 'Montant initial',
      'shift_total_sales': 'Total ventes',
      'shift_expected_amount': 'Montant attendu',
      'shift_notes': 'Notes (Optionnel)',
      'shift_close': 'Clôturer',
      'shift_close_dialog': 'Fermer',
      'shift_no_shift_text': 'Jour sans caisse',
      'shift_no_shift_desc': "Il n'y a pas de caisse ouverte pour aujourd'hui",

      // ── Products ──
      'prod_name': 'Nom du Produit',
      'prod_barcode': 'Code-barres',
      'prod_buy_price': "Prix d'achat (DA)",
      'prod_sell_price': 'Prix de vente (DA)',
      'prod_size': 'Pointure',
      'prod_color': 'Couleur',
      'prod_stock': 'Stock',
      'prod_add_variant': 'Ajouter Variante',
      'prod_edit_variant': 'Modifier Variante',
      'prod_archive_variant': 'Archiver cette variante',
      'prod_variant_updated': 'Variante mise à jour avec succès.',
      'prod_low_stock': 'Stock faible',
      'prod_image': 'Image',
      'prod_add_title': 'Ajouter Produit',
      'prod_edit_title': 'Modifier Produit',
      'prod_save': 'Enregistrer',
      'prod_variants': 'Variantes',
      'prod_add_variant_btn': 'Ajouter une variante',
      'prod_remove_variant': 'Supprimer la variante',
      'prod_add_product_success': 'Produit ajouté avec succès !',
      'prod_search_hint': 'Rechercher un produit ou fournisseur...',
      'prod_edit_price_code': 'Modifier Prix/Code',
      'prod_no_results': 'Aucun produit trouvé',
      'prod_variants_count': 'variantes',
      'prod_total_stock': 'Stock total',

      // ── Inventory ──
      'inv_title': 'Inventaire',
      'inv_search_hint': 'Rechercher un produit (Nom, Code-barres, Taille, Couleur)...',
      'inv_filter_store': 'Filtrer par magasin',
      'inv_total_stock': 'Stock total',
      'inv_total_value': 'Valeur totale',
      'inv_no_results': 'Aucun produit trouvé.',
      'inv_all_stores': 'Tous les Magasins',
      'inv_low_stock': 'Stock faible uniquement',
      'inv_transfer': 'Transfert de stock',
      'inv_variant_details': 'Détails de la variante',
      'inv_summary': 'Résumé',
      'inv_products': 'produits',
      'inv_value': 'Valeur',

      // ── Customers ──
      'cust_title': 'Gestion des Clients',
      'cust_search_hint': 'Rechercher un client...',
      'cust_add': 'Nouveau Client',
      'cust_full_name': 'Nom complet',
      'cust_phone': 'Téléphone',
      'cust_email': 'Adresse e-mail',
      'cust_address': 'Adresse',
      'cust_balance': 'Solde',
      'cust_receive_payment': 'Recevoir un paiement',
      'cust_payment_recorded': 'Paiement enregistré avec succès.',
      'cust_archived': 'Client archivé.',
      'cust_restored': 'Client restauré.',
      'cust_tabs_info': 'Informations',
      'cust_tabs_invoices': 'Factures',
      'cust_tabs_payments': 'Paiements',
      'cust_no_client_selected': 'Sélectionnez un client pour voir les détails',
      'cust_payment_amount': 'Montant reçu',
      'cust_payment_notes': 'Notes / Motif',
      'cust_no_results': 'Aucun client trouvé.',
      'cust_active': 'Actifs',
      'cust_inactive': 'Archivés',
      'cust_debt': 'Dette',

      // ── Suppliers ──
      'supp_title': 'Gestion des Fournisseurs',
      'supp_search_hint': 'Rechercher un fournisseur...',
      'supp_add': 'Nouveau Fournisseur',
      'supp_company': 'Nom de la société',
      'supp_contact': 'Nom du contact',
      'supp_balance': 'Solde',
      'supp_payment_recorded': 'Versement enregistré.',
      'supp_archived': 'Fournisseur archivé.',
      'supp_tabs_info': 'Informations',
      'supp_tabs_purchases': 'Achats',
      'supp_tabs_payments': 'Versements',
      'supp_payment_amount': 'Montant versé',
      'supp_payment_notes': 'Notes / Motif',
      'supp_no_results': 'Aucun fournisseur trouvé.',
      'supp_no_selected': 'Sélectionnez un fournisseur pour voir les détails',
      'supp_active': 'Actifs',
      'supp_inactive': 'Archivés',

      // ── Employees ──
      'emp_title': 'Gestion des Employés',
      'emp_add': 'Ajouter un employé',
      'emp_delete': 'Supprimer',
      'emp_assign_store': 'Affecter au magasin',
      'emp_created': 'Employé créé avec succès !',
      'emp_deleted': 'Employé supprimé avec succès.',
      'emp_name': 'Nom complet',
      'emp_email': 'Adresse e-mail',
      'emp_password': 'Mot de passe',
      'emp_confirm_delete': 'Confirmer la suppression',
      'emp_delete_confirm_msg': 'Voulez-vous vraiment supprimer cet employé ?',
      'emp_delete_warning': 'Cette action est irréversible.',
      'emp_add_btn': "Créer l'employé",
      'emp_list_title': 'Liste des employés',

      // ── Stores ──
      'store_title': 'Gestion des Magasins',
      'store_add': 'Nouveau Magasin',
      'store_name': 'Nom du Magasin',
      'store_created': 'Magasin créé avec succès.',
      'store_no_results': 'Aucun magasin trouvé.',

      // ── Expenses ──
      'exp_title': 'Gestion des Dépenses',
      'exp_add': 'Nouvelle Dépense',
      'exp_category': 'Catégorie',
      'exp_category_add': 'Ajouter catégorie',
      'exp_category_title': 'Catégories de Dépenses',
      'exp_category_hint': 'Nom de la catégorie',
      'exp_method': 'Méthode de paiement',
      'exp_month_total': 'Total du mois',
      'exp_count': 'Nombre',
      'exp_max': 'Plus grande',
      'exp_recorded': 'Dépense enregistrée.',
      'exp_amount': 'Montant (DA)',
      'exp_date': 'Date de la dépense',
      'exp_change_date': 'Changer',
      'exp_no_category': 'Sans catégorie',
      'exp_no_results': 'Aucune dépense enregistrée.',
      'exp_manage_categories': 'Gérer les catégories',
      'exp_period': 'Période',
      'exp_all_categories': 'Toutes',
      'exp_expenses_label': 'dépenses',

      // ── Debt Recovery ──
      'debt_title': 'Recouvrement des Dettes',
      'debt_search_hint': 'Rechercher un client...',
      'debt_total_debt': 'Total dettes',
      'debt_receive_payment': 'Recevoir un paiement',
      'debt_payment_history': 'Historique des paiements',
      'debt_client_info': 'Infos client',
      'debt_new_balance': 'Nouveau solde',
      'debt_recorded': 'Paiement enregistré avec succès.',
      'debt_current_balance': 'Solde actuel',
      'debt_amount_received': 'Montant reçu (DA)',
      'debt_notes': 'Notes (optionnel)',
      'debt_confirm_payment': 'Confirmer le paiement',
      'debt_no_debt': 'Aucun client endetté!',
      'debt_no_payments': 'Aucun paiement de recouvrement.',
      'debt_clients_count': 'clients endettés',
      'debt_select_client': 'Sélectionnez un client pour voir les détails',
      'debt_not_specified': 'Non renseigné',

      // ── Dashboard ──
      'dash_title': 'Tableau de Bord',
      'dash_today_sales': "Ventes d'aujourd'hui",
      'dash_month_sales': 'Ventes du mois',
      'dash_top_products': 'Produits les plus vendus',
      'dash_revenue': 'Chiffre d\'affaires',
      'dash_expenses_month': 'Dépenses du mois',
      'dash_net_profit': 'Bénéfice net',
      'dash_last_month': 'Mois dernier',
      'dash_this_month': 'Ce mois-ci',
      'dash_today': "Aujourd'hui",
      'dash_stores_comparison': 'Comparaison des magasins',
      'dash_welcome': 'Bienvenue',
      'dash_overview': "Vue d'ensemble",
      'dash_evolution': 'Évolution des Ventes',
      'dash_7days': '7 derniers jours',
      'dash_customer_debt': 'Créances Clients',
      'dash_supplier_debt': 'Dettes Fournisseurs',
      'dash_stock_value': 'Valeur du Stock',
      'dash_active_cust': 'Clients Actifs',
      'dash_active_supp': 'Fournisseurs Actifs',
      'dash_credits_in_progress': 'Crédits en cours',
      'dash_to_settle': 'À régler',

      // ── Sales History ──
      'sales_title': 'Historique des Ventes',
      'sales_search': 'Rechercher',
      'sales_invoice': 'Facture',
      'sales_status_paid': 'Payé ✓',
      'sales_status_partial': 'Partiel',
      'sales_status_unpaid': 'Impayé',
      'sales_status_refunded': 'Remboursé ↩ / مُرجَع',
      'sales_status_returned': 'Retourné',
      'sales_status_cancelled': 'Annulé',
      'sales_no_results': 'Aucune vente trouvée.',
      'sales_all_stores': 'Tous les Magasins',
      'sales_report': 'Rapport',
      'sales_customer': 'Client',
      'sales_store': 'Magasin',
      'sales_refund': 'Remboursement',

      // ── Refund ──
      'refund_title': 'Retour de produits',
      'refund_select_items': 'Sélectionnez les articles à retourner :',
      'refund_reason': 'Raison du retour (optionnel)',
      'refund_confirm': 'Confirmer le retour',
      'refund_success': 'Retour effectué avec succès. ID:',
      'refund_min_one_item': 'Veuillez sélectionner au moins un article à retourner',
      'refund_quantity': 'Quantité retournée :',
      'refund_original_invoice': 'Facture originale :',
      'refund_total_amount': 'Montant total du retour :',
      'refund_unit_price': 'Prix :',

      // ── Activity Logs ──
      'log_title': "Journaux d'activité",
      'log_action': 'Action',
      'log_user': 'Utilisateur',
      'log_date': 'Date',
      'log_no_results': 'Aucun journal trouvé.',

      // ── Messages success ──
      'msg_saved': 'Enregistré avec succès.',
      'msg_deleted': 'Supprimé avec succès.',
      'msg_payment_recorded': 'Paiement enregistré avec succès.',
      'msg_sale_recorded': 'Vente enregistrée avec succès.',
      'msg_updated': 'Mis à jour avec succès.',
      'msg_archived': 'Archivé avec succès.',
      'msg_restored': 'Restauré avec succès.',

      // ── Messages error ──
      'msg_error': 'Erreur',
      'msg_access_denied': 'Accès refusé : Autorisations insuffisantes',
      'msg_invalid_amount': 'Montant invalide',
      'msg_required': 'Requis',
      'msg_load_error': 'Erreur de chargement',
      'msg_connection_error': 'Erreur de connexion',
      'msg_invalid': 'Invalide',

      // ── Offline ──
      'offline_mode': 'Mode hors ligne',
      'offline_banner': 'Vous êtes en mode hors ligne',
      'offline_pending': 'opérations en attente',
      'offline_sync': 'Synchronisation',
      'offline_connected': 'Mode Hors-ligne (connecté)',
      'offline_synced': 'Synchronisé ✓',
      'offline_sync_now': 'Synchroniser maintenant',
      'online_mode': 'En ligne',

      // ── Settings ──
      'settings_language': 'Langue',
      'settings_ar': 'العربية',
      'settings_fr': 'Français',

      // ── Currency & Misc ──
      'misc_currency': 'DA',
      'misc_no_results': 'Aucun résultat.',
      'misc_loading': 'Chargement...',
      'misc_select_store': 'Sélectionnez un magasin',
      'misc_not_available': 'N/A',
      'misc_unknown': 'Inconnu',
      'misc_walk_in': 'Passager',
      'misc_no_phone': 'Sans téléphone',
      'misc_no_email': 'Sans email',
      'misc_no_store': 'Aucun magasin',
      'label_added_on': 'Ajouté le :',

      // ── Mode selection ──
      'mode_title': 'Choisir le mode',
      'mode_online': 'En ligne',
      'mode_online_desc': 'Accès temps réel (Recommandé)',
      'mode_offline': 'Hors ligne',
      'mode_offline_desc': 'Travailler sans internet',
      'mode_seeding': 'Initialisation de la base locale...',
      'mode_syncing': 'Synchronisation initiale en cours...',
      'mode_ready': 'Données locales disponibles ✓',
      'mode_no_store': 'Erreur: Aucun magasin assigné.',

      // ── Purchases ──
      'purchase_title': 'Achats Fournisseur',
      'purchase_add': 'Nouvel Achat',
      'purchase_amount_paid': 'Montant payé au fournisseur',
      'purchase_supplier': 'Fournisseur',
      'purchase_store': 'Magasin de réception',
      'purchase_product': 'Produit (Variante)',
      'purchase_quantity': 'Quantité',
      'purchase_unit_price': "Prix d'achat unitaire",
      'purchase_no_results': 'Aucun achat trouvé.',

      // ── Owner dashboard (mobile) ──
      'owner_inventory': 'Inventaire',
      'owner_analytics': 'Analytiques',
      'owner_profile': 'Profil',
      'owner_new_password': 'Nouveau mot de passe',
      'owner_confirm_password': 'Confirmer le mot de passe',
      'owner_min_chars': 'Minimum 6 caractères.',
      'owner_passwords_mismatch': 'Les mots de passe ne correspondent pas.',
      'owner_password_changed': 'Mot de passe modifié avec succès ✅',
      'owner_product_not_found': 'Produit introuvable.',
      'owner_change_password': 'Changer le mot de passe',

      // ── Dates ──
      'day_mon': 'Lun', 'day_tue': 'Mar', 'day_wed': 'Mer', 'day_thu': 'Jeu', 'day_fri': 'Ven', 'day_sat': 'Sam', 'day_sun': 'Dim',
      'month_1': 'Jan', 'month_2': 'Fév', 'month_3': 'Mar', 'month_4': 'Avr', 'month_5': 'Mai', 'month_6': 'Jun',
      'month_7': 'Jul', 'month_8': 'Aoû', 'month_9': 'Sep', 'month_10': 'Oct', 'month_11': 'Nov', 'month_12': 'Déc',
    },

    // ────────────────────────────────────────────────────────────
    // ARABIC
    // ────────────────────────────────────────────────────────────
    'ar': {
      // ── Navigation ──
      'nav_dashboard': 'لوحة التحكم',
      'nav_products': 'المنتجات',
      'nav_add_product': 'إضافة منتج',
      'nav_inventory': 'المخزون',
      'nav_sales': 'سجل المبيعات',
      'nav_clients': 'العملاء',
      'nav_suppliers': 'الموردون',
      'nav_employees': 'الموظفون',
      'nav_stores': 'المتاجر',
      'nav_pos': 'نقطة البيع',
      'nav_shifts': 'إدارة الوردية',
      'nav_activity': 'سجل النشاطات',
      'nav_expenses': 'المصاريف',
      'nav_recovery': 'تحصيل الديون',
      'nav_settings': 'الإعدادات',
      'nav_purchases': 'مشتريات الموردين',

      // ── Common actions ──
      'action_save': 'حفظ',
      'action_cancel': 'إلغاء',
      'action_delete': 'حذف',
      'action_confirm': 'تأكيد',
      'action_close': 'إغلاق',
      'action_refresh': 'تحديث',
      'action_add': 'إضافة',
      'action_edit': 'تعديل',
      'action_archive': 'أرشفة',
      'action_search': 'بحث',
      'action_filter': 'تصفية',
      'action_print': 'طباعة',
      'action_export': 'تصدير',
      'action_restore': 'استعادة',

      // ── Common labels ──
      'label_name': 'الاسم',
      'label_phone': 'الهاتف',
      'label_email': 'البريد الإلكتروني',
      'label_address': 'العنوان',
      'label_amount': 'المبلغ',
      'label_date': 'التاريخ',
      'label_notes': 'ملاحظات',
      'label_status': 'الحالة',
      'label_store': 'المتجر',
      'label_balance': 'الرصيد',
      'label_total': 'المجموع',
      'label_quantity': 'الكمية',
      'label_price': 'السعر',
      'label_description': 'الوصف',
      'label_category': 'التصنيف',
      'label_method': 'طريقة الدفع',
      'label_cash': 'نقداً',
      'label_bank': 'تحويل بنكي',
      'label_mobile': 'جوال',
      'label_active': 'نشط',
      'label_archived': 'مؤرشف',
      'label_all': 'الكل',
      'label_role': 'الدور',
      'label_role_admin': 'المدير',
      'label_password': 'كلمة المرور',
      'label_supplier': 'المورد',
      'label_product': 'المنتج',

      // ── Auth ──
      'auth_title': 'تسجيل الدخول',
      'auth_email': 'البريد الإلكتروني',
      'auth_password': 'كلمة المرور',
      'auth_login': 'دخول',
      'auth_logout': 'تسجيل الخروج',
      'auth_error_invalid': 'البريد أو كلمة المرور غير صحيحة.',
      'auth_connecting': 'جاري الاتصال...',
      'auth_welcome': 'مرحباً',
      'auth_subtitle': 'نظام إدارة المخزون',
      'auth_forgot_password': 'نسيت كلمة المرور؟',
      'auth_access_denied_mobile': 'غير مسموح: التطبيق المحمول مخصص للمالك فقط.',
      'auth_profile_not_found': 'الملف الشخصي غير موجود. اتصل بالمسؤول.',
      'auth_connection_error': 'خطأ في الاتصال: تعذر التحقق من الملف الشخصي. تحقق من الإنترنت.',
      'auth_fill_fields': 'الرجاء ملء جميع الحقول.',
      'auth_error_generic': 'حدث خطأ غير متوقع.',
      'auth_welcome_msg': 'مرحباً، سجل الدخول للمتابعة',
      'auth_no_account': 'ليس لديك حساب؟ ',
      'auth_register_here': 'سجل هنا',

      // ── POS ──
      'pos_title': 'نقطة البيع',
      'pos_search_hint': 'البحث عن منتج أو مسح الباركود...',
      'pos_new_sale': 'بيع جديد',
      'pos_today_invoices': 'فواتير اليوم',
      'pos_checkout': 'الدفع',
      'pos_validate_sale': 'تأكيد البيع',
      'pos_cart_empty': 'عربة التسوق فارغة',
      'pos_add_to_cart': 'أضف إلى العربة',
      'pos_total': 'المبلغ الإجمالي :',
      'pos_paid': 'المبلغ المدفوع (د.ج)',
      'pos_remaining': 'المتبقي',
      'pos_sale_success': 'تم تسجيل البيع! تم تحديث الفاتورة والمخزون.',
      'pos_walk_in_customer': 'زبون عابر',
      'pos_scanner_active': 'الماسح نشط',
      'pos_no_shift_warning': 'لا توجد وردية مفتوحة',
      'pos_client_optional': 'العميل (اختياري)',
      'pos_debt_note': 'سيُضاف المتبقي إلى ديون العميل.',
      'pos_walk_in_note': 'زبون عابر: الدفع الكامل مطلوب (لا يمكن البيع بالدين).',
      'pos_enter_valid_price': 'الرجاء إدخال سعر صالح لكل منتج.',
      'pos_select_store': 'الرجاء اختيار المتجر.',
      'pos_stock_empty': 'تنبيه: المخزون نفد في هذا المتجر.',
      'pos_no_product': 'لم يتم العثور على منتج',
      'pos_invoice': 'فاتورة',
      'pos_client': 'العميل',
      'pos_time': 'الوقت',
      'pos_credit': 'دين (غير مسدد)',
      'pos_paid_status': 'مدفوع',
      'pos_no_invoice_today': 'لا توجد فواتير مسجلة اليوم.',
      'pos_store_not_selected': 'لم يتم اختيار المتجر',
      'pos_report': 'التقرير',
      'pos_size': 'المقاس',
      'pos_color': 'اللون',
      'pos_code': 'الكود',
      'pos_payment_notes': 'دفع في نقطة البيع للفاتورة',
      'pos_unit_price': 'سعر الوحدة',
      'pos_system_error': 'خطأ في النظام',
      'pos_cart_title': 'العربة',
      'pos_items': 'عناصر',

      // ── Shifts ──
      'shift_open_title': 'فتح الوردية',
      'shift_close_title': 'إغلاق الوردية',
      'shift_opening_amount': 'المبلغ الابتدائي (د.ج)',
      'shift_closing_amount': 'المبلغ الفعلي في الصندوق',
      'shift_actual_amount': 'المبلغ الفعلي في الصندوق',
      'shift_report_title': 'تقرير اليوم',
      'shift_surplus': 'فائض',
      'shift_shortage': 'عجز',
      'shift_no_shift': 'يوم بدون وردية',
      'shift_open_success': 'تم فتح الوردية بنجاح',
      'shift_close_success': 'تم إغلاق الوردية',
      'shift_previous_unclosed': 'وردية غير مغلقة',
      'shift_previous_unclosed_msg': 'هناك وردية من تاريخ {date} لم يتم إغلاقها.',
      'shift_ignore': 'تجاهل',
      'shift_close_old': 'إغلاق القديمة',
      'shift_skip': 'بدون وردية',
      'shift_open': 'فتح الوردية',
      'shift_enter_amount': 'الرجاء إدخال المبلغ',
      'shift_invalid_amount': 'مبلغ غير صحيح',
      'shift_open_error': 'حدث خطأ أثناء فتح الوردية',
      'shift_retrieve_error': 'خطأ في استرجاع الوردية',
      'shift_instructions': 'أدخل المبلغ الموجود في الصندوق لبدء يوم العمل',
      'shift_initial_amount': 'المبلغ الابتدائي',
      'shift_total_sales': 'مجموع المبيعات',
      'shift_expected_amount': 'المبلغ المتوقع',
      'shift_notes': 'ملاحظات (اختياري)',
      'shift_close': 'إغلاق',
      'shift_close_dialog': 'إغلاق',
      'shift_no_shift_text': 'يوم بدون وردية',
      'shift_no_shift_desc': 'لا توجد وردية مفتوحة اليوم',

      // ── Products ──
      'prod_name': 'اسم المنتج',
      'prod_barcode': 'الباركود',
      'prod_buy_price': 'سعر الشراء (د.ج)',
      'prod_sell_price': 'سعر البيع (د.ج)',
      'prod_size': 'المقاس',
      'prod_color': 'اللون',
      'prod_stock': 'المخزون',
      'prod_add_variant': 'إضافة صنف',
      'prod_edit_variant': 'تعديل صنف',
      'prod_archive_variant': 'أرشفة هذا الصنف',
      'prod_variant_updated': 'تم تحديث الصنف بنجاح.',
      'prod_low_stock': 'مخزون منخفض',
      'prod_image': 'الصورة',
      'prod_add_title': 'إضافة منتج',
      'prod_edit_title': 'تعديل منتج',
      'prod_save': 'حفظ',
      'prod_variants': 'الأصناف',
      'prod_add_variant_btn': 'إضافة صنف جديد',
      'prod_remove_variant': 'حذف الصنف',
      'prod_add_product_success': 'تمت إضافة المنتج بنجاح!',
      'prod_search_hint': 'البحث عن منتج أو مورد...',
      'prod_edit_price_code': 'تعديل السعر/الكود',
      'prod_no_results': 'لم يتم العثور على منتجات',
      'prod_variants_count': 'أصناف',
      'prod_total_stock': 'المخزون الكلي',

      // ── Inventory ──
      'inv_title': 'المخزون',
      'inv_search_hint': 'البحث عن منتج (الاسم، الباركود، المقاس، اللون)...',
      'inv_filter_store': 'تصفية حسب المتجر',
      'inv_total_stock': 'إجمالي المخزون',
      'inv_total_value': 'القيمة الإجمالية',
      'inv_no_results': 'لم يتم العثور على منتجات.',
      'inv_all_stores': 'جميع المتاجر',
      'inv_low_stock': 'المخزون المنخفض فقط',
      'inv_transfer': 'نقل المخزون',
      'inv_variant_details': 'تفاصيل الصنف',
      'inv_summary': 'ملخص',
      'inv_products': 'منتجات',
      'inv_value': 'القيمة',

      // ── Customers ──
      'cust_title': 'إدارة العملاء',
      'cust_search_hint': 'البحث عن عميل...',
      'cust_add': 'عميل جديد',
      'cust_full_name': 'الاسم الكامل',
      'cust_phone': 'الهاتف',
      'cust_email': 'البريد الإلكتروني',
      'cust_address': 'العنوان',
      'cust_balance': 'الرصيد',
      'cust_receive_payment': 'استلام دفعة',
      'cust_payment_recorded': 'تم تسجيل الدفعة بنجاح.',
      'cust_archived': 'تم أرشفة العميل.',
      'cust_restored': 'تم استعادة العميل.',
      'cust_tabs_info': 'معلومات',
      'cust_tabs_invoices': 'الفواتير',
      'cust_tabs_payments': 'المدفوعات',
      'cust_no_client_selected': 'اختر عميلاً لعرض التفاصيل',
      'cust_payment_amount': 'المبلغ المستلم',
      'cust_payment_notes': 'ملاحظات / السبب',
      'cust_no_results': 'لم يتم العثور على عملاء.',
      'cust_active': 'نشطون',
      'cust_inactive': 'مؤرشفون',
      'cust_debt': 'الدين',

      // ── Suppliers ──
      'supp_title': 'إدارة الموردين',
      'supp_search_hint': 'البحث عن مورد...',
      'supp_add': 'مورد جديد',
      'supp_company': 'اسم الشركة',
      'supp_contact': 'اسم جهة الاتصال',
      'supp_balance': 'الرصيد',
      'supp_payment_recorded': 'تم تسجيل الدفعة.',
      'supp_archived': 'تم أرشفة المورد.',
      'supp_tabs_info': 'معلومات',
      'supp_tabs_purchases': 'المشتريات',
      'supp_tabs_payments': 'الدفعات',
      'supp_payment_amount': 'المبلغ المدفوع',
      'supp_payment_notes': 'ملاحظات / السبب',
      'supp_no_results': 'لم يتم العثور على موردين.',
      'supp_no_selected': 'اختر مورداً لعرض التفاصيل',
      'supp_active': 'نشطون',
      'supp_inactive': 'مؤرشفون',

      // ── Employees ──
      'emp_title': 'إدارة الموظفين',
      'emp_add': 'إضافة موظف',
      'emp_delete': 'حذف',
      'emp_assign_store': 'تعيين في متجر',
      'emp_created': 'تم إنشاء الموظف بنجاح!',
      'emp_deleted': 'تم حذف الموظف بنجاح.',
      'emp_name': 'الاسم الكامل',
      'emp_email': 'البريد الإلكتروني',
      'emp_password': 'كلمة المرور',
      'emp_confirm_delete': 'تأكيد الحذف',
      'emp_delete_confirm_msg': 'هل تريد حقاً حذف هذا الموظف؟',
      'emp_delete_warning': 'هذا الإجراء لا رجعة فيه.',
      'emp_add_btn': 'إنشاء الموظف',
      'emp_list_title': 'قائمة الموظفين',

      // ── Stores ──
      'store_title': 'إدارة المتاجر',
      'store_add': 'متجر جديد',
      'store_name': 'اسم المتجر',
      'store_created': 'تم إنشاء المتجر بنجاح.',
      'store_no_results': 'لم يتم العثور على متاجر.',

      // ── Expenses ──
      'exp_title': 'إدارة المصاريف',
      'exp_add': 'مصروف جديد',
      'exp_category': 'التصنيف',
      'exp_category_add': 'إضافة تصنيف',
      'exp_category_title': 'تصنيفات المصاريف',
      'exp_category_hint': 'اسم التصنيف',
      'exp_method': 'طريقة الدفع',
      'exp_month_total': 'إجمالي الشهر',
      'exp_count': 'العدد',
      'exp_max': 'الأكبر',
      'exp_recorded': 'تم تسجيل المصروف.',
      'exp_amount': 'المبلغ (د.ج)',
      'exp_date': 'تاريخ المصروف',
      'exp_change_date': 'تغيير',
      'exp_no_category': 'بدون تصنيف',
      'exp_no_results': 'لا توجد مصاريف مسجلة.',
      'exp_manage_categories': 'إدارة التصنيفات',
      'exp_period': 'الفترة',
      'exp_all_categories': 'الكل',
      'exp_expenses_label': 'مصاريف',

      // ── Debt Recovery ──
      'debt_title': 'تحصيل الديون',
      'debt_search_hint': 'البحث عن عميل...',
      'debt_total_debt': 'إجمالي الديون',
      'debt_receive_payment': 'استلام دفعة',
      'debt_payment_history': 'سجل المدفوعات',
      'debt_client_info': 'معلومات العميل',
      'debt_new_balance': 'الرصيد الجديد',
      'debt_recorded': 'تم تسجيل الدفعة بنجاح.',
      'debt_current_balance': 'الرصيد الحالي',
      'debt_amount_received': 'المبلغ المستلم (د.ج)',
      'debt_notes': 'ملاحظات (اختياري)',
      'debt_confirm_payment': 'تأكيد الدفع',
      'debt_no_debt': 'لا يوجد عملاء مدينون!',
      'debt_no_payments': 'لا توجد مدفوعات تحصيل.',
      'debt_clients_count': 'عملاء مدينون',
      'debt_select_client': 'اختر عميلاً لعرض التفاصيل',
      'debt_not_specified': 'غير محدد',

      // ── Dashboard ──
      'dash_title': 'لوحة التحكم',
      'dash_today_sales': 'مبيعات اليوم',
      'dash_month_sales': 'مبيعات الشهر',
      'dash_top_products': 'الأكثر مبيعاً',
      'dash_revenue': 'الإيرادات',
      'dash_expenses_month': 'مصاريف الشهر',
      'dash_net_profit': 'صافي الربح',
      'dash_last_month': 'الشهر الماضي',
      'dash_this_month': 'هذا الشهر',
      'dash_today': 'اليوم',
      'dash_stores_comparison': 'مقارنة المتاجر',
      'dash_welcome': 'مرحباً',
      'dash_overview': 'نظرة عامة',
      'dash_evolution': 'تطور المبيعات',
      'dash_7days': 'آخر 7 أيام',
      'dash_customer_debt': 'ديون العملاء',
      'dash_supplier_debt': 'ديون الموردين',
      'dash_stock_value': 'قيمة المخزون',
      'dash_active_cust': 'العملاء النشطون',
      'dash_active_supp': 'الموردون النشطون',
      'dash_credits_in_progress': 'ديون قيد التحصيل',
      'dash_to_settle': 'ديون للموردين',

      // ── Sales History ──
      'sales_title': 'سجل المبيعات',
      'sales_search': 'بحث',
      'sales_invoice': 'فاتورة',
      'sales_status_paid': 'مدفوع ✓',
      'sales_status_partial': 'جزئي',
      'sales_status_unpaid': 'غير مدفوع',
      'sales_status_refunded': 'مُرجَع ↩',
      'sales_status_returned': 'مُعاد',
      'sales_status_cancelled': 'مُلغى',
      'sales_no_results': 'لم يتم العثور على مبيعات.',
      'sales_all_stores': 'جميع المتاجر',
      'sales_report': 'التقرير',
      'sales_customer': 'العميل',
      'sales_store': 'المتجر',
      'sales_refund': 'إرجاع',

      // ── Refund ──
      'refund_title': 'إرجاع المشتريات',
      'refund_select_items': 'حدد العناصر التي سيتم إرجاعها:',
      'refund_reason': 'سبب الإرجاع (اختياري)',
      'refund_confirm': 'تأكيد الإرجاع',
      'refund_success': 'تمت عملية الإرجاع بنجاح. معرف:',
      'refund_min_one_item': 'الرجاء تحديد عنصر واحد على الأقل للإرجاع',
      'refund_quantity': 'الكمية المرجعة:',
      'refund_original_invoice': 'الفاتورة الأصلية:',
      'refund_total_amount': 'إجمالي مبلغ الإرجاع:',
      'refund_unit_price': 'السعر:',

      // ── Activity Logs ──
      'log_title': 'سجل النشاطات',
      'log_action': 'الإجراء',
      'log_user': 'المستخدم',
      'log_date': 'التاريخ',
      'log_no_results': 'لا توجد سجلات.',

      // ── Messages success ──
      'msg_saved': 'تم الحفظ بنجاح.',
      'msg_deleted': 'تم الحذف بنجاح.',
      'msg_payment_recorded': 'تم تسجيل الدفعة بنجاح.',
      'msg_sale_recorded': 'تم تسجيل البيع بنجاح.',
      'msg_updated': 'تم التحديث بنجاح.',
      'msg_archived': 'تم الأرشفة بنجاح.',
      'msg_restored': 'تم الاستعادة بنجاح.',

      // ── Messages error ──
      'msg_error': 'خطأ',
      'msg_access_denied': 'تم رفض الوصول: صلاحيات غير كافية',
      'msg_invalid_amount': 'مبلغ غير صالح',
      'msg_required': 'مطلوب',
      'msg_load_error': 'خطأ في التحميل',
      'msg_connection_error': 'خطأ في الاتصال',
      'msg_invalid': 'غير صالح',

      // ── Offline ──
      'offline_mode': 'وضع عدم الاتصال',
      'offline_banner': 'أنت في وضع عدم الاتصال',
      'offline_pending': 'عمليات معلقة',
      'offline_sync': 'مزامنة',
      'offline_connected': 'وضع عدم الاتصال (متصل)',
      'offline_synced': 'تم المزامنة ✓',
      'offline_sync_now': 'مزامنة الآن',
      'online_mode': 'متصل',

      // ── Settings ──
      'settings_language': 'اللغة',
      'settings_ar': 'العربية',
      'settings_fr': 'Français',

      // ── Currency & Misc ──
      'misc_currency': 'د.ج',
      'misc_no_results': 'لا توجد نتائج.',
      'misc_loading': 'جاري التحميل...',
      'misc_select_store': 'اختر متجراً',
      'misc_not_available': 'غ/م',
      'misc_unknown': 'غير معروف',
      'misc_walk_in': 'زبون عابر',
      'misc_no_phone': 'بدون هاتف',
      'misc_no_email': 'بدون بريد',
      'misc_no_store': 'بدون متجر',
      'label_added_on': 'أضيف في :',

      // ── Mode selection ──
      'mode_title': 'اختيار الوضع',
      'mode_online': 'متصل',
      'mode_online_desc': 'وصول مباشر (مُوصى به)',
      'mode_offline': 'غير متصل',
      'mode_offline_desc': 'العمل بدون إنترنت',
      'mode_seeding': 'تهيئة القاعدة المحلية...',
      'mode_syncing': 'جاري المزامنة الأولية...',
      'mode_ready': 'البيانات المحلية جاهزة ✓',
      'mode_no_store': 'خطأ: لا يوجد متجر مخصص.',

      // ── Purchases ──
      'purchase_title': 'مشتريات الموردين',
      'purchase_add': 'شراء جديد',
      'purchase_amount_paid': 'المبلغ المدفوع للمورد',
      'purchase_supplier': 'المورد',
      'purchase_store': 'متجر الاستلام',
      'purchase_product': 'المنتج (الصنف)',
      'purchase_quantity': 'الكمية',
      'purchase_unit_price': 'سعر الشراء للوحدة',
      'purchase_no_results': 'لم يتم العثور على مشتريات.',

      // ── Owner dashboard (mobile) ──
      'owner_inventory': 'المخزون',
      'owner_analytics': 'التحليلات',
      'owner_profile': 'الملف الشخصي',
      'owner_new_password': 'كلمة مرور جديدة',
      'owner_confirm_password': 'تأكيد كلمة المرور',
      'owner_min_chars': 'الحد الأدنى 6 أحرف.',
      'owner_passwords_mismatch': 'كلمتا المرور غير متطابقتين.',
      'owner_password_changed': 'تم تغيير كلمة المرور بنجاح ✅',
      'owner_product_not_found': 'المنتج غير موجود.',
      'owner_change_password': 'تغيير كلمة المرور',

      // ── Dates ──
      'day_mon': 'الإثنين', 'day_tue': 'الثلاثاء', 'day_wed': 'الأربعاء', 'day_thu': 'الخميس', 'day_fri': 'الجمعة', 'day_sat': 'السبت', 'day_sun': 'الأحد',
      'month_1': 'جانفي', 'month_2': 'فيفري', 'month_3': 'مارس', 'month_4': 'أفريل', 'month_5': 'ماي', 'month_6': 'جوان',
      'month_7': 'جويلية', 'month_8': 'أوت', 'month_9': 'سبتمبر', 'month_10': 'أكتوبر', 'month_11': 'نوفمبر', 'month_12': 'ديسمبر',
    },
  };
}
