import 'package:flutter/material.dart';

/// Centralized bilingual string management for ShoeStock ERP.
/// Usage: S.t('key') for static access, S.of(context, 'key') with BuildContext.
class S {
  static String _locale = 'ar';

  static void setLocale(String lang) {
    _locale = lang;
  }

  static String get currentLocale => _locale;

  /// Context-aware lookup (same result as t(), provided for API symmetry).
  static String of(BuildContext context, String key) => t(key);

  /// Static lookup — safe in initState, build, async callbacks.
  static String t(String key) => _strings[_locale]?[key] ?? '[$key]';

  // ══════════════════════════════════════════════════════════════
  // Translation maps
  // ══════════════════════════════════════════════════════════════

  static const Map<String, Map<String, String>> _strings = {
    // ────────────────────────────────────────────────────────────
    // FRENCH
    // ────────────────────────────────────────────────────────────
    'fr': {
      // ── Navigation ──
      'nav_dashboard': 'Tableau de Bord',
      'nav_products': 'Produits',
      'nav_add_product': 'Ajouter Produit',
      'nav_inventory': 'Inventaire',
      'nav_size_runs': 'Tailles',
      'nav_sales': 'Historique Ventes',
      'nav_clients': 'Clients',
      'nav_suppliers': 'Fournisseurs',
      'nav_employees': 'Employés',
      'nav_stores': 'Magasins',
      'nav_pos': 'Point de Vente',
      'nav_shifts': 'Gestion Caisse',
      'nav_activity': "Journaux d'activité",
      'nav_expenses': 'Dépenses',
      'nav_recovery': 'Recouvrement',
      'nav_settings': 'Paramètres',
      'nav_purchases': 'Achats Fournisseur',

      // ── Common actions ──
      'action_save': 'Enregistrer',
      'action_cancel': 'Annuler',
      'action_delete': 'Supprimer',
      'action_confirm': 'Confirmer',
      'action_close': 'Fermer',
      'action_refresh': 'Actualiser',
      'action_add': 'Ajouter',
      'action_edit': 'Modifier',
      'action_archive': 'Archiver',
      'action_search': 'Rechercher',
      'action_filter': 'Filtrer',
      'action_print': 'Imprimer',
      'action_export': 'Exporter',
      'action_restore': 'Restaurer',
      'action_confirm_delete': 'Confirmer la suppression',
      'action_add_to_list': 'Ajouter à la liste',

      // ── Common labels ──
      'label_name': 'Nom',
      'label_phone': 'Téléphone',
      'label_email': 'Adresse e-mail',
      'label_address': 'Adresse',
      'label_amount': 'Montant',
      'label_date': 'Date',
      'label_notes': 'Notes',
      'label_status': 'Statut',
      'label_store': 'Magasin',
      'label_balance': 'Solde',
      'label_total': 'Total',
      'label_quantity': 'Quantité',
      'label_price': 'Prix',
      'label_description': 'Description',
      'label_category': 'Catégorie',
      'label_method': 'Méthode de paiement',
      'label_cash': 'Espèces',
      'label_bank': 'Virement bancaire',
      'label_mobile': 'Mobile',
      'label_active': 'Actif',
      'label_archived': 'Archivé',
      'label_all': 'Tous',
      'label_role': 'Rôle',
      'label_role_admin': 'Administrateur',
      'label_password': 'Mot de passe',
      'label_supplier': 'Fournisseur',
      'label_product': 'Produit',
      'label_stock': 'Stock',
      'label_actions': 'Actions',
      'label_unit_price': 'Prix unitaire',
      'label_qty_short': 'Qté:',
      'label_phone_short': 'Tél: ',
      'label_added_on': 'Ajouté le :',

      // ── Auth ──
      'auth_title': 'Connexion',
      'auth_email': 'Adresse e-mail',
      'auth_password': 'Mot de passe',
      'auth_login': 'Se connecter',
      'auth_logout': 'Déconnexion',
      'logout_confirm_msg': 'Voulez-vous vraiment vous déconnecter ?',
      'auth_error_invalid': 'E-mail ou mot de passe incorrect.',
      'auth_connecting': 'Connexion en cours...',
      'auth_welcome': 'Bienvenue',
      'auth_subtitle': 'Système de gestion de stock',
      'auth_forgot_password': 'Mot de passe oublié ?',
      'auth_access_denied_mobile': 'Accès refusé : Mobile réservé au Propriétaire.',
      'auth_profile_not_found': "Profil utilisateur introuvable. Contactez l'administrateur.",
      'auth_connection_error': 'Erreur de connexion : Impossible de vérifier le profil. Veuillez vérifier votre internet.',
      'auth_error_email': "L'adresse e-mail n'est pas valide.",
      'auth_fill_fields': 'Veuillez remplir tous les champs.',
      'pin_enter_title': 'Entrez votre code PIN',
      'pin_setup_title': 'Définir un code PIN (4 chiffres)',
      'pin_confirm_title': 'Confirmer le code PIN',
      'pin_auth_biometric_reason': 'Authentifiez-vous pour déverrouiller',
      'pin_setup_biometric': 'Activer la reconnaissance biométrique ?',
      'pin_mismatch': 'Les codes ne correspondent pas',
      'pin_incorrect': 'Code PIN incorrect',
      'auth_error_generic': "Une erreur inattendue s'est produite.",
      'auth_welcome_msg': 'Bienvenue, connectez-vous pour continuer',
      'auth_no_account': "Vous n'avez pas de compte ? ",
      'auth_register_here': 'Inscrivez-vous ici',

      // ── POS ──
      'pos_checkout': 'Encaissement',
      'pos_add_to_cart': 'Ajouter au panier',
      'pos_total': 'Total à payer :',
      'pos_walk_in_customer': 'Client Comptoir',
      'pos_scanner_active': 'Scan actif',
      'pos_no_shift_warning': 'Aucune caisse ouverte',
      'pos_debt_note': 'Le reste sera ajouté aux dettes (crédit) du client.',
      'pos_walk_in_note': 'Client Comptoir : Le paiement complet est exigé (Pas de crédit possible).',
      'pos_enter_valid_price': 'Veuillez saisir un prix unitaire valide pour chaque article.',
      'pos_select_store': 'Veuillez sélectionner un magasin.',
      'pos_stock_empty': 'Attention: Stock épuisé pour ce magasin.',
      'pos_no_product': 'Aucun produit trouvé',
      'pos_paid_status': 'Payé',
      'pos_no_invoice_today': "Aucune facture enregistrée aujourd'hui.",
      'pos_store_not_selected': 'Magasin non sélectionné',
      'pos_report': 'Rapport',
      'pos_size': 'Taille',
      'pos_color': 'Couleur',
      'pos_code': 'Code',
      'pos_payment_notes': 'Paiement à la caisse pour facture',
      'pos_unit_price': 'Prix U',
      'pos_system_error': 'Erreur système',
      'pos_cart_title': 'Panier',
      'pos_items': 'articles',
      'pos_title': 'Point de Vente (POS)',
      'pos_new_sale': 'Nouvelle Vente',
      'pos_today_invoices': 'Factures du Jour',
      'pos_report_btn': 'Rapport / تقرير اليوم',
      'pos_search_hint': 'Rechercher un produit ou scanner un code-barres...',
      'pos_no_products': 'Aucun produit trouvé',
      'pos_add_btn': 'Ajouter',
      'pos_cart_empty': 'Le panier est vide',
      'pos_qty_short': 'Qté: ',
      'pos_client_optional': 'Client (Optionnel)',
      'pos_walkin_client': 'Client Comptoir (Passager)',
      'pos_total_to_pay': 'Total à payer',
      'pos_pay_btn': 'Payer',
      'pos_no_store_selected': 'Magasin non sélectionné',
      'pos_no_today_invoices': "Aucune facture enregistrée aujourd'hui.",
      'pos_invoice': 'Facture:',
      'pos_client': 'Client:',
      'pos_time': 'Heure:',
      'pos_status': 'Statut:',
      'pos_credit_unpaid': 'Crédit (Non soldé)',
      'pos_paid': 'Payé',
      'pos_remaining': 'Reste:',
      'pos_cashout_title': 'Encaissement',
      'pos_total_to_pay_lbl': 'Total à payer :',
      'pos_walkin_warning': 'Client Comptoir : Le paiement complet est exigé (Pas de crédit possible).',
      'pos_amount_received': 'Montant encaissé',
      'pos_credit_note': 'Le reste sera ajouté aux dettes (crédit) du client.',
      'pos_validate_sale': 'Valider la Vente',
      'pos_select_store_first': 'Veuillez sélectionner un magasin.',
      'pos_stock_empty_warning': 'Attention: Stock épuisé pour ce magasin.',
      'pos_stock_insufficient': 'Stock insuffisant — seulement',
      'pos_stock_available': 'disponible(s)',
      'pos_out_of_stock': 'Rupture de stock',
      'pos_stock_badge': 'Stock:',
      'pos_item_oos': 'n\'est plus en stock',
      'pos_invalid_price': 'Veuillez saisir un prix unitaire valide pour chaque article.',
      'pos_sale_success': 'Vente enregistrée ! Facture et stocks mis à jour.',
      'pos_access_denied': 'Accès refusé : Autorisations insuffisantes',
      'pos_payment_method': 'Mode de paiement',
      'pos_cash': 'Espèces',
      'pos_credit': 'Crédit',
      'pos_mixed': 'Mixte',
      'pos_client_balance_current': 'Solde actuel du client:',
      'pos_balance_new_warning': 'Nouveau solde après vente:',
      'pos_cash_amount': 'Montant espèces',
      'pos_credit_amount': 'Montant crédit',
      'pos_credit_client_only': 'Crédit réservé aux clients enregistrés',
      'pos_stock_changed_title': 'Stock modifié',
      'pos_stock_changed_msg': 'Le stock de certains articles a changé. Quantités ajustées.',
      'pos_inv_search_hint': 'Rechercher par client ou numéro...',
      'pos_inv_filter_all': 'Tous',
      'pos_inv_filter_paid': 'Payé',
      'pos_inv_filter_credit': 'Crédit',
      'pos_inv_page_prev': 'Précédent',
      'pos_inv_page_next': 'Suivant',
      'pos_inv_page_of': 'Page {current} / {total}',
      'pos_inv_articles': 'Articles:',
      'pos_inv_discount': 'Remise:',
      'pos_inv_paid_label': 'Payé:',
      'pos_inv_remaining_label': 'Reste dû:',
      'pos_inv_mode': 'Mode:',
      'pos_inv_seller': 'Vendeur:',
      'pos_inv_reprint': 'Réimprimer ticket',
      'pos_inv_print_pending': 'Impression en cours de développement',
      'pos_inv_no_items': 'Aucun article',
      'pos_inv_credit_status': 'Crédit',
      'pos_discount_percent': '%',
      'pos_discount_fixed': 'DA',
      'pos_discount_apply': 'Appliquer',
      'pos_discount_subtotal': 'Sous-total',
      'pos_discount_remise_lbl': 'Remise',
      'pos_discount_exceeds': 'Remise dépasse le maximum autorisé ({max}%)',
      'pos_discount_limit': 'Limite de remise',
      'pos_discount_apply_max': 'Appliquer max',
      'pos_credit_limit': 'Plafond de crédit:',
      'pos_credit_limit_exceeded': 'Montant du crédit dépasse le plafond autorisé! Solde: {balance}, Plafond: {limit}',
      'pos_customer_balance': 'Solde:',
      'pos_customer_credit_limit': 'Plafond:',
      'store_max_discount': 'Remise maximale (%)',
      'pos_cart_clear': 'Vider',
      'pos_cart_clear_confirm': 'Vider le panier ?',
      'pos_cart_clear_yes': 'Oui, vider',
      'pos_cart_clear_no': 'Annuler',
      'pos_print_title': 'Impression des tickets',
      'pos_print_ask': 'Voulez-vous imprimer automatiquement un ticket après chaque vente aujourd\'hui ?',
      'pos_print_always': 'Oui, toujours imprimer',
      'pos_print_manual': 'Non, demander à chaque fois',
      'pos_print_auto_label': 'Auto',
      'pos_print_manual_label': 'Manuel',
      'pos_print_auto_msg': 'Ticket envoyé à l\'impression',
      'pos_print_now': 'Imprimer le ticket',
      'pos_print_ignore': 'Ignorer',
      'pos_change_label': 'Monnaie rendue:',
      'pos_insufficient': 'Montant insuffisant',
      'pos_confirm_payment': 'Confirmer la vente',
      'pos_price_label': 'Prix',
      'pos_new_price_label': 'Nouveau prix',
      'pos_online_status': 'En ligne',
      'pos_offline_status': 'Hors ligne',
      'pos_pending_ops': 'opération(s) en attente',
      'pos_error': 'Erreur:',
      'pos_refund_btn': 'Retourner la vente',
      'pos_return_resell_btn': 'Retour + Revente',
      'pos_refund_title': 'Retour de vente',
      'pos_refund_warning': 'Cette action est irréversible. Le stock sera restauré et la vente annulée.',
      'pos_refund_select_items': 'Sélectionner les articles à retourner:',
      'pos_refund_total': 'Montant à rembourser:',
      'pos_refund_reason': 'Motif du retour',
      'pos_refund_reason_hint': 'Ex: article défectueux...',
      'pos_refund_confirm': 'Confirmer le retour',
      'pos_refund_success': 'Retour effectué avec succès',
      'pos_print_auto_short': '🖨️ Auto',
      'pos_print_manual_short': '🖨️ Manuel',

      // ── Shifts ──
      'shift_open_title': 'Ouverture de caisse',
      'shift_close_title': 'Clôturer la caisse',
      'shift_opening_amount': 'Montant initial (DA)',
      'shift_closing_amount': 'Montant réel en caisse',
      'shift_actual_amount': 'Montant réel en caisse',
      'shift_report_title': 'Rapport du jour',
      'shift_surplus': 'Surplus',
      'shift_shortage': 'Déficit',
      'shift_no_shift': 'Jour sans caisse',
      'shift_open_success': 'Caisse ouverte avec succès',
      'shift_close_success': 'Caisse clôturée avec succès',
      'shift_previous_unclosed': "Caisse non clôturée",
      'shift_previous_unclosed_msg': "Une caisse du {date} n'a pas été clôturée.",
      'shift_ignore': 'Ignorer',
      'shift_close_old': "Clôturer l'ancienne",
      'shift_skip': 'Sans caisse',
      'shift_open': 'Ouvrir la caisse',
      'shift_enter_amount': 'Veuillez entrer le montant',
      'shift_invalid_amount': 'Montant invalide',
      'shift_open_error': "Erreur d'ouverture de caisse",
      'shift_retrieve_error': 'Erreur de récupération de la caisse',
      'shift_instructions': "Entrez le montant initial en caisse pour aujourd'hui",
      'shift_initial_amount': 'Montant initial',
      'shift_total_sales': 'Total ventes',
      'shift_expected_amount': 'Montant attendu',
      'shift_notes': 'Notes (Optionnel)',
      'shift_close': 'Clôturer',
      'shift_close_dialog': 'Fermer',
      'shift_no_shift_text': 'Jour sans caisse',
      'shift_no_shift_desc': "Il n'y a pas de caisse ouverte pour aujourd'hui",

      // ── Products ──
      'prod_name': 'Nom du Produit',
      'prod_barcode': 'Code-barres',
      'prod_buy_price': "Prix d'achat (DA)",
      'prod_sell_price': 'Prix de vente (DA)',
      'prod_size': 'Pointure',
      'prod_color': 'Couleur',
      'prod_stock': 'Stock',
      'prod_add_variant': 'Ajouter Variante',
      'prod_edit_variant': 'Modifier Variante',
      'prod_archive_variant': 'Archiver cette variante',
      'prod_variant_updated': 'Variante mise à jour avec succès.',
      'prod_title': 'Gestion des Produits',
      'prod_list': 'Liste des Produits',
      'prod_add': 'Ajouter un Produit',
      'prod_add_title': 'Ajouter un Produit',
      'prod_desc': 'Description',
      'prod_saved': 'Produit enregistré avec succès.',
      'prod_catalog_title': 'Catalogue des Produits',
      'prod_add_btn': 'Ajouter un Produit',
      'prod_search_hint': 'Rechercher un produit ou fournisseur...',
      'prod_active_count': 'Produits Actifs',
      'prod_no_results': 'Aucun produit trouvé',
      'prod_no_supplier': 'Sans fournisseur',
      'prod_variants_count': 'variantes',
      'prod_stock_label': 'Stock: ',
      'prod_no_active_variants': 'Aucune variante active.',
      'prod_details': 'Détails',
      'prod_buy_sell_margin': 'Achat / Vente (Marge)',
      'prod_out_of_stock': 'Pas en stock',
      'prod_edit_price_code': 'Modifier Prix/Code',
      'prod_archive_variant_title': 'Archiver cette variante ?',
      'prod_archive_variant_msg': 'Elle ne sera plus disponible pour la vente, mais restera dans les anciennes factures.',
      'prod_archive_title': 'Archiver TOUT le produit ?',
      'prod_archive_msg': 'Le produit et toutes ses variantes seront masqués du catalogue.',
      'prod_archive_btn': 'Archiver le produit',
      'prod_buy_short': 'A: ',
      'prod_sell_short': 'V: ',
      'prod_margin_short': 'Marge: +',
      'prod_add_variant_btn': 'Ajouter une variante',
      'prod_remove_variant': 'Supprimer la variante',
      'prod_add_product_success': 'Produit ajouté avec succès !',
      'prod_price_note': "Note: Les anciennes factures garderont l'ancien prix.",
      'prod_total_stock': 'Stock Total',
      'prod_no_permission': "Vous n'avez pas la permission d'ajouter des produits",
      'prod_buy_price_hidden': '---',

      // ── Inventory ──
      'inv_title': 'Inventaire',
      'inv_search_hint': 'Rechercher un produit (Nom, Code-barres, Taille, Couleur)...',
      'inv_filter_store': 'Filtrer par magasin',
      'inv_total_stock': 'Stock total',
      'inv_total_value': 'Valeur totale',
      'inv_no_results': 'Aucun produit trouvé.',
      'inv_all_stores': 'Tous les Magasins',
      'inv_low_stock': 'Stock faible uniquement',
      'inv_transfer': 'Transfert de stock',
      'inv_variant_details': 'Détails de la variante',
      'inv_summary': 'Résumé',
      'inv_products': 'produits',
      'inv_value': 'Valeur',
      'inv_dashboard_title': 'Tableau de Bord: Inventaire & Flux',
      'inv_no_store_msg': "Aucun magasin. Ajoutez d'abord un magasin.",
      'inv_stat_total_products': 'Total Produits',
      'inv_stat_total_stock': 'Stock Total',
      'inv_units': 'unités',
      'inv_stat_total_value': 'Valeur (Achat)',
      'inv_stat_low_stock': 'Stock Faible',
      'inv_no_products': 'Aucun produit dans ce magasin',
      'inv_low_stock_alerts': 'Alertes Stock Faible (< 3)',
      'inv_no_alerts': 'Aucune alerte. Le stock est bon!',
      'inv_recent_movements': 'Derniers Flux (Entrées / Sorties)',
      'inv_no_movements': 'Aucun mouvement récent',
      'inv_mov_in': 'Acheté',
      'inv_mov_out': 'Vendu',
      'inv_read_only': 'Stock — consultation uniquement',

      // ── Misc ──
      'misc_by': 'par',
      'misc_system': 'Système',
      'misc_currency': 'DA',
      'misc_no_results': 'Aucun résultat.',
      'misc_loading': 'Chargement...',
      'misc_select_store': 'Sélectionnez un magasin',
      'misc_not_available': 'N/A',
      'misc_unknown': 'Inconnu',
      'misc_online_only': 'Disponible uniquement en ligne',
      'misc_end_of_list': 'Fin de la liste',
      'misc_walk_in': 'Passager',
      'misc_no_phone': 'Sans téléphone',
      'misc_no_email': 'Sans email',
      'misc_no_store': 'Aucun magasin',
      'inv_mov_return': 'Retour',
      'action_load_more': 'Charger plus',

      // ── Purchases ──
      'buy_title': 'Achat / Approvisionnement',
      'buy_qty_invalid': 'La quantité doit être supérieure à 0.',
      'buy_fill_fields': 'Veuillez remplir tous les champs et ajouter des articles.',
      'buy_validation_title': 'Validation et Paiement',
      'buy_total_invoice': 'Total de la facture :',
      'buy_amount_paid': 'Montant payé au fournisseur',
      'buy_payment_note': 'Note: Si vous payez moins que le total, le reste sera automatiquement ajouté aux dettes (crédit) du fournisseur.',
      'buy_confirm': "Confirmer l'achat",
      'buy_success': 'Facture enregistrée ! Stocks et comptes mis à jour automatiquement.',
      'buy_add_items': 'Ajouter des articles',
      'buy_store_receiving': 'Magasin de réception',
      'buy_my_store': 'Mon magasin',
      'buy_product_variant': 'Produit (Variante)',
      'buy_no_permission': "Vous n'avez pas la permission d'enregistrer des achats",
      'buy_read_only': 'Consultation uniquement — achats non autorisés',
      'buy_receipt': "Bon d'achat",
      'buy_items': 'articles',
      'buy_no_items': 'Aucun article ajouté.',
      'buy_validate_pay': 'Valider et Payer',

      // ── Customers ──
      'cust_title': 'Gestion des Clients',
      'cust_title_full': 'Gestion des Clients & Crédits',
      'cust_search_hint': 'Rechercher un client...',
      'cust_add': 'Nouveau Client',
      'cust_add_tooltip': 'Ajouter un client',
      'cust_edit': 'Modifier le Client',
      'cust_full_name': 'Nom complet',
      'cust_phone': 'Téléphone',
      'cust_email': 'Adresse e-mail',
      'cust_address': 'Adresse',
      'cust_balance': 'Solde',
      'cust_receive_payment': 'Recevoir un paiement',
      'cust_payment_recorded': 'Paiement enregistré avec succès.',
      'cust_archived': 'Client archivé.',
      'cust_restored': 'Client restauré.',
      'cust_tabs_info': 'Informations',
      'cust_tabs_invoices': 'Factures',
      'cust_tabs_payments': 'Paiements',
      'cust_no_client_selected': 'Sélectionnez un client pour voir les détails',
      'cust_payment_amount': 'Montant reçu',
      'cust_payment_notes': 'Notes / Motif',
      'cust_no_results': 'Aucun client trouvé.',
      'cust_active': 'Actifs',
      'cust_inactive': 'Archivés',
      'cust_debt': 'Dette',
      'cust_updated': 'Client modifié.',
      'cust_added': 'Client ajouté.',
      'cust_archive_title': 'Archiver le client',
      'cust_archive_msg': 'Voulez-vous masquer ce client ? (Ses factures seront conservées).',
      'cust_manual_payment': 'Versement manuel (Client)',
      'cust_with_debt': 'Endettés',
      'cust_register_payment_btn': 'Enregistrer un paiement (Versement)',
      'cust_no_purchases': 'Aucun achat enregistré.',
      'cust_payment_of': 'Paiement de',

      // ── Suppliers ──
      'supp_title': 'Gestion des Fournisseurs',
      'supp_search_hint': 'Rechercher un fournisseur...',
      'supp_add': 'Nouveau Fournisseur',
      'supp_company': 'Nom de la société',
      'supp_contact': 'Nom du contact',
      'supp_balance': 'Solde',
      'supp_payment_recorded': 'Versement enregistré.',
      'supp_archived': 'Fournisseur archivé.',
      'supp_tabs_info': 'Informations',
      'supp_tabs_purchases': 'Achats',
      'supp_tabs_payments': 'Versements',
      'supp_payment_amount': 'Montant versé',
      'supp_payment_notes': 'Notes / Motif',
      'supp_no_results': 'Aucun fournisseur trouvé.',
      'supp_no_selected': 'Sélectionnez un fournisseur pour voir les détails',
      'supp_active': 'Actifs',
      'supp_inactive': 'Archivés',
      'supp_with_debt': 'Seulement endettés',
      'supp_edit': 'Modifier le Fournisseur',
      'supp_archive_title': 'Archiver le fournisseur',
      'supp_archive_msg': 'Voulez-vous masquer ce fournisseur ? (Ses anciennes factures seront conservées).',
      'supp_no_debt': 'Aucun fournisseur avec des dettes.',
      'supp_contact_prefix': 'Contact: ',
      'supp_debt_credit': 'Dettes (Crédit)',
      'supp_new_payment': 'Nouveau Versement',
      'supp_current_debt': 'Dette actuelle: ',
      'supp_manual_payment': 'Versement manuel',
      'supp_make_payment': 'Verser un montant',
      'supp_no_invoices': "Aucune facture d'achat pour ce fournisseur.",
      'supp_no_payments': 'Aucun versement enregistré.',
      'supp_payment_of': 'Versement de ',
      'supp_reason': 'Motif: ',
      'supp_compare': 'Comparer',

      // ── Supplier Comparison ──
      'comparison_select_product': 'Sélectionner un produit',
      'comparison_search_hint': 'Rechercher par nom ou code-barres...',
      'comparison_no_variants': 'Aucun produit trouvé',
      'comparison_title': 'Comparaison',
      'comparison_no_data': 'Aucune donnée de comparaison pour ce produit',
      'comparison_supplier': 'Fournisseur',
      'comparison_last_price': 'Dernier prix',
      'comparison_avg_price': 'Prix moyen',
      'comparison_min_price': 'Min',
      'comparison_max_price': 'Max',
      'comparison_purchases': 'Achats',

      // ── Employees ──
      'emp_title': 'Gestion des Employés',
      'emp_add': 'Ajouter un employé',
      'emp_add_btn': "Créer l'employé",
      'emp_edit': "Modifier l'employé",
      'emp_edit_btn': 'Enregistrer les modifications',
      'emp_delete': 'Supprimer',
      'emp_assign_store': 'Affecter au magasin',
      'emp_created': 'Employé créé avec succès !',
      'emp_updated': 'Employé modifié avec succès.',
      'emp_deleted': 'Employé supprimé avec succès.',
      'emp_suspended': 'Employé suspendu avec succès.',
      'emp_reactivated': 'Employé réactivé avec succès.',
      'emp_archived': 'Employé archivé définitivement.',
      'emp_name': 'Nom complet',
      'emp_first_name': 'Prénom',
      'emp_last_name': 'Nom',
      'emp_email': 'Adresse e-mail',
      'emp_password': 'Mot de passe',
      'emp_password_optional': 'Laisser vide pour ne pas modifier',
      'emp_phone': 'Téléphone',
      'emp_address': 'Adresse',
      'emp_job_title': 'Poste / Fonction',
      'emp_hired_at': "Date d'embauche",
      'emp_since_date': 'Depuis le',
      'emp_work_duration': 'Durée de travail',
      'emp_confirm_delete': 'Confirmer la suppression',
      'emp_delete_confirm_msg': 'Voulez-vous vraiment supprimer cet employé ?\n\nCette action est irréversible et supprimera son compte.',
      'emp_delete_warning': 'Cette action est irréversible.',
      'emp_confirm_suspend': "Suspendre l'employé ?",
      'emp_confirm_suspend_msg': "L'employé ne pourra plus se connecter. Vous pourrez le réactiver plus tard.",
      'emp_confirm_archive': 'Archiver définitivement ?',
      'emp_confirm_archive_msg': "Cette action est irréversible. L'employé sera définitivement masqué de toutes les listes.",
      'emp_list_title': 'Liste des employés',
      'emp_no_permission': "Vous n'avez pas accès à la liste des employés",
      'emp_no_results': 'Aucun employé trouvé.',
      'emp_select_hint': 'Sélectionnez un employé pour voir ses détails',
      'emp_active_tab': 'Actifs',
      'emp_suspended_tab': 'Suspendus',
      'emp_archived_tab': 'Archivés',
      'emp_suspend_btn': 'Suspendre',
      'emp_reactivate_btn': 'Réactiver',
      'emp_archive_btn': 'Archiver définitivement',
      'emp_status_active': 'Actif',
      'emp_status_suspended': 'Suspendu',
      'emp_status_archived': 'Archivé',
      'emp_role_label': 'Employé',
      'emp_search_hint': 'Rechercher un employé...',

      // ── Stores ──
      'store_title': 'Gestion des Magasins',
      'store_add': 'Nouveau Magasin',
      'store_name': 'Nom du Magasin',
      'store_created': 'Magasin créé avec succès.',
      'store_no_results': 'Aucun magasin trouvé.',
      'store_edit': 'Modifier Magasin',
      'store_updated': 'Magasin modifié avec succès.',
      'store_delete_msg': "Voulez-vous supprimer le magasin '{name}' ?\n\nLe magasin ne sera supprimé que s'il n'est pas lié à des employés ou à du stock.",
      'store_deleted': 'Magasin supprimé avec succès.',
      'store_delete_error': "Impossible de supprimer le magasin (il peut être lié à d'autres données).",
      'store_no_results_yet': 'Aucun magasin pour le moment',
      'store_add_first': 'Ajoutez votre premier magasin pour commencer',
      'store_add_btn': 'Ajouter un magasin',
      'store_employees': 'employés',
      'store_units': 'unités',

      // ── Expenses ──
      'exp_title': 'Gestion des Dépenses',
      'exp_add': 'Nouvelle Dépense',
      'exp_category': 'Catégorie',
      'exp_category_add': 'Ajouter catégorie',
      'exp_category_title': 'Catégories de Dépenses',
      'exp_category_hint': 'Nom de la catégorie',
      'exp_method': 'Méthode de paiement',
      'exp_month_total': 'Total du mois',
      'exp_count': 'Nombre',
      'exp_max': 'Plus grande',
      'exp_recorded': 'Dépense enregistrée.',
      'exp_amount': 'Montant (DA)',
      'exp_date': 'Date de la dépense',
      'exp_change_date': 'Changer',
      'exp_no_category': 'Sans catégorie',
      'exp_no_results': 'Aucune dépense enregistrée.',
      'exp_manage_categories': 'Gérer les catégories',
      'exp_period': 'Période',
      'exp_all_categories': 'Toutes',
      'exp_expenses_label': 'dépenses',

      // ── Debt Recovery ──
      'debt_title': 'Recouvrement des Dettes',
      'debt_search_hint': 'Rechercher un client...',
      'debt_total_debt': 'Total dettes',
      'debt_receive_payment': 'Recevoir un paiement',
      'debt_payment_history': 'Historique des paiements',
      'debt_client_info': 'Infos client',
      'debt_new_balance': 'Nouveau solde',
      'debt_recorded': 'Paiement enregistré avec succès.',
      'debt_current_balance': 'Solde actuel',
      'debt_amount_received': 'Montant reçu (DA)',
      'debt_notes': 'Notes (optionnel)',
      'debt_confirm_payment': 'Confirmer le paiement',
      'debt_no_debt': 'Aucun client endetté!',
      'debt_no_payments': 'Aucun paiement de recouvrement.',
      'debt_clients_count': 'clients endettés',
      'debt_select_client': 'Sélectionnez un client pour voir les détails',
      'debt_not_specified': 'Non renseigné',
      'debt_overdue_clients': 'clients en retard de paiement',
      'debt_days_overdue': 'Retard',
      'debt_days': 'jours',

      // ── Dashboard ──
      'dash_title': 'Tableau de Bord',
      'dash_today_sales': "Ventes d'aujourd'hui",
      'dash_month_sales': 'Ventes du mois',
      'dash_top_products': 'Produits les plus vendus',
      'dash_revenue': "Chiffre d'affaires",
      'dash_expenses_month': 'Dépenses du mois',
      'dash_net_profit': 'Bénéfice net',
      'dash_last_month': 'Mois dernier',
      'dash_this_month': 'Ce mois-ci',
      'dash_today': "Aujourd'hui",
      'dash_stores_comparison': 'Comparaison des magasins',
      'dash_welcome': 'Bienvenue',
      'dash_overview': "Vue d'ensemble",
      'dash_evolution': 'Évolution des Ventes',
      'dash_7days': '7 derniers jours',
      'dash_customer_debt': 'Créances Clients',
      'dash_supplier_debt': 'Dettes Fournisseurs',
      'dash_total_profit': 'Profit Total',
      'dash_avg_margin': 'Marge Moy.',
      'dash_stock_value': 'Valeur du Stock',
      'dash_active_cust': 'Clients Actifs',
      'dash_active_supp': 'Fournisseurs Actifs',
      'dash_credits_in_progress': 'Crédits en cours',
      'dash_to_settle': 'À régler',
      'dash_day_mon': 'Lun',
      'dash_day_tue': 'Mar',
      'dash_day_wed': 'Mer',
      'dash_day_thu': 'Jeu',
      'dash_day_fri': 'Ven',
      'dash_day_sat': 'Sam',
      'dash_day_today': 'Auj',
      // ── Dashboard (new) ──
      'dash_today_sales_count': 'Factures du jour',
      'dash_today_expenses': 'Dépenses du jour',
      'dash_low_stock': 'Stock faible',
      'dash_revenue_chart': "Évolution du chiffre d'affaires",
      'dash_period': 'Période',
      'dash_week': '7 jours',
      'dash_3months': '90 jours',
      'dash_no_data': 'Aucune donnée',
      'dash_recent_activity': 'Activité récente',
      'dash_no_activity': 'Aucune activité récente',
      'dash_ranking': 'Rang',
      'dash_product_name': 'Produit',
      'dash_sold_qty': 'Qté vendue',
      'dash_total_revenue': 'Revenu',
      'dash_no_products_sold': 'Aucun produit vendu ce mois',
      'dash_debt_clients': 'Clients débiteurs',
      'dash_no_debt_clients': 'Aucun client débiteur',
      'dash_my_sales': 'Mes ventes',
      'dash_my_sales_today': "Mes ventes aujourd'hui",
      'dash_no_sales': 'Aucune vente enregistrée',
      'dash_sales_count': 'Nb ventes',
      'dash_item_count': 'articles',
      'dash_month': '30 jours',
      'dash_today_revenue': 'Revenu du jour',
      'dash_employee_dashboard': 'Tableau de bord employé',

      // ── Sales History ──
      'sales_title': 'Historique des Ventes',
      'sales_search': 'Rechercher',
      'sales_invoice': 'Facture',
      'sales_status_paid': 'Payé ✓',
      'sales_status_partial': 'Partiel',
      'sales_status_unpaid': 'Impayé',
      'sales_status_refunded': 'Remboursé ↩ / مُرجَع',
      'sales_status_returned': 'Retourné',
      'sales_status_cancelled': 'Annulé',
      'sales_no_results': 'Aucune vente trouvée.',
      'sales_all_stores': 'Tous les Magasins',
      'sales_report': 'Rapport',
      'sales_customer': 'Client',
      'sales_store': 'Magasin',
      'sales_refund': 'Remboursement',
      'sales_sold_by': 'Vendu par',

      // ── Refund ──
      'refund_title': 'Retour de produits',
      'refund_select_items': 'Sélectionnez les articles à retourner :',
      'refund_reason': 'Raison du retour (optionnel)',
      'refund_confirm': 'Confirmer le retour',
      'refund_success': 'Retour effectué avec succès. ID:',
      'refund_min_one_item': 'Veuillez sélectionner au moins un article à retourner',
      'refund_quantity': 'Quantité retournée :',
      'refund_original_invoice': 'Facture originale :',
      'refund_total_amount': 'Montant total du retour :',
      'refund_unit_price': 'Prix :',
      'refund_48h_blocked': 'Retour impossible après 48h de la vente',
      'refund_48h_warning_title': 'Attention: Délai dépassé',
      'refund_48h_warning_body': 'Attention: cette facture date de plus de 48h. Continuer quand même?',
      'refund_48h_continue': 'Continuer le retour',
      'refund_invoice_age': 'Vendu il y a {hours}h',

      // ── Activity Logs ──
      'log_title': "Journaux d'activité",
      'log_action': 'Action',
      'log_user': 'Utilisateur',
      'log_date': 'Date',
      'log_no_results': 'Aucun journal trouvé.',
      'label_performed_action': 'a effectué',
      'label_date_from': 'Du',
      'label_date_to': 'Au',
      'log_filter_action': 'Filtrer par action',
      'log_filter_date': 'Filtrer par date',
      'log_load_more': 'Charger plus',
      'log_no_more': 'Aucun résultat supplémentaire',
      'log_all_actions': 'Toutes les actions',
      'log_reset_filters': 'Réinitialiser les filtres',
      'log_results_count': 'résultats',
      'label_sale': 'Vente',
      'label_supply': 'Achat fournisseur',
      'label_return': 'Retour',
      'label_create_employee': 'Création employé',
      'label_update_employee': 'Modification employé',
      'label_suspend_employee': 'Suspension employé',
      'label_reactivate_employee': 'Réactivation employé',
      'label_permanent_delete_employee': 'Archivage employé',
      'label_delete_employee': 'Suppression employé',
      'label_add_expense': 'Dépense',
      'label_add_debt_recovery': 'Recouvrement',
      'label_remaining': 'Restant',
      'label_refund': 'Remboursement',

      // ── Messages success ──
      'msg_saved': 'Enregistré avec succès.',
      'msg_deleted': 'Supprimé avec succès.',
      'msg_payment_recorded': 'Paiement enregistré avec succès.',
      'msg_sale_recorded': 'Vente enregistrée avec succès.',
      'msg_updated': 'Mis à jour avec succès.',
      'msg_archived': 'Archivé avec succès.',
      'msg_restored': 'Restauré avec succès.',

      // ── Messages error ──
      'msg_error': 'Erreur',
      'msg_access_denied': 'Accès refusé : Autorisations insuffisantes',
      'msg_invalid_amount': 'Montant invalide',
      'msg_required': 'Requis',
      'msg_load_error': 'Erreur de chargement',
      'msg_connection_error': 'Erreur de connexion',
      'msg_invalid': 'Invalide',
      'msg_min_4_chars': 'Minimum 4 caractères.',

      // ── Offline ──
      'offline_mode': 'Mode hors ligne',
      'offline_banner': 'Vous êtes en mode hors ligne',
      'offline_pending': 'opérations en attente',
      'offline_sync': 'Synchronisation',
      'offline_connected': 'Mode Hors-ligne (connecté)',
      'offline_synced': 'Synchronisé ✓',
      'offline_sync_now': 'Synchroniser maintenant',
      'online_mode': 'En ligne',

      // ── Settings ──
      'settings_language': 'Langue',
      'settings_ar': 'العربية',
      'settings_fr': 'Français',

      // ── Mode selection ──
      'mode_title': 'Choisir le mode',
      'mode_online': 'En ligne',
      'mode_online_desc': 'Accès temps réel (Recommandé)',
      'mode_offline': 'Hors ligne',
      'mode_offline_desc': 'Travailler sans internet',
      'mode_seeding': 'Initialisation de la base locale...',
      'mode_syncing': 'Synchronisation initiale en cours...',
      'mode_ready': 'Données locales disponibles ✓',
      'mode_no_store': 'Erreur: Aucun magasin assigné.',

      // ── Purchases (supplier) ──
      'purchase_title': 'Achats Fournisseur',
      'purchase_add': 'Nouvel Achat',
      'purchase_amount_paid': 'Montant payé au fournisseur',
      'purchase_supplier': 'Fournisseur',
      'purchase_store': 'Magasin de réception',
      'purchase_product': 'Produit (Variante)',
      'purchase_quantity': 'Quantité',
      'purchase_unit_price': "Prix d'achat unitaire",
      'purchase_no_results': 'Aucun achat trouvé.',

      // ── Owner dashboard (mobile) ──
      'owner_inventory': 'Inventaire',
      'owner_analytics': 'Analytiques',
      'owner_profile': 'Profil',
      'owner_new_password': 'Nouveau mot de passe',
      'owner_confirm_password': 'Confirmer le mot de passe',
      'owner_min_chars': 'Minimum 6 caractères.',
      'owner_passwords_mismatch': 'Les mots de passe ne correspondent pas.',
      'owner_password_changed': 'Mot de passe modifié avec succès ✅',
      'owner_product_not_found': 'Produit introuvable.',
      'owner_change_password': 'Changer le mot de passe',
      'owner_scanner_title': 'Scanner (Mode Propriétaire)',
      'owner_buy_price': 'Prix Achat:',
      'owner_sell_price': 'Prix Vente:',
      'owner_net_margin': 'Marge Nette:',
      'owner_stocks_per_store': 'Stocks par magasin:',
      'owner_dash_title': 'Tableau de Bord Maître',
      'owner_financial_health': 'Santé Financière (Aujourd\'hui)',
      'owner_store_performance': 'Performance par Magasin',
      'owner_qty_remaining': 'restants',
      'owner_recent_activities': 'Activités Récentes',
      'owner_inv_all_stores': 'Inventaire — Tous les Magasins',
      'owner_no_items_stock': 'Aucun article en stock.',
      'owner_sales_section': 'Ventes',
      'owner_vs_last_month': 'vs Mois dernier',
      'owner_top_5_products': 'Top 5 Produits (ce mois)',
      'owner_qty_sold': 'vendus',
      'owner_store_comp_today': 'Comparaison Magasins (aujourd\'hui)',
      'auth_logout_confirm': 'Voulez-vous vraiment vous déconnecter ?',
      'owner_role_label': 'Propriétaire',

      // ── Contact / WhatsApp / SMS ──
      'contact_whatsapp_msg': 'Bonjour {name}, votre solde de {amount} DA est en retard de {days} jours.',
      'contact_sms_msg': 'Bonjour {name}, votre solde dû: {amount}. Merci de régulariser. Cordialement.',
      'contact_no_phone': 'Aucun numéro de téléphone pour ce client',
      'contact_debt_list_title': 'Clients débiteurs',
      'contact_send_reminder': 'Envoyer un rappel',
      'debt_whatsapp_reminder': 'Rappel WhatsApp',
      'debt_sms_reminder': 'Rappel SMS',

      // ── Dates ──
      'day_mon': 'Lun', 'day_tue': 'Mar', 'day_wed': 'Mer', 'day_thu': 'Jeu', 'day_fri': 'Ven', 'day_sat': 'Sam', 'day_sun': 'Dim',
      'month_1': 'Jan', 'month_2': 'Fév', 'month_3': 'Mar', 'month_4': 'Avr', 'month_5': 'Mai', 'month_6': 'Jun',
      'month_7': 'Jul', 'month_8': 'Aoû', 'month_9': 'Sep', 'month_10': 'Oct', 'month_11': 'Nov', 'month_12': 'Déc',

      // ── Filters ──
      'filter_all': 'Tous',
      'filter_men': 'Homme',
      'filter_women': 'Femme',
      'filter_kid': 'Enfant',
      'filter_instock': 'En stock',
      'filter_low_stock': 'Faible',
      'filter_out_of_stock': 'Rupture',
      'filter_active': 'Actifs',
      'filter_suspended': 'Suspendus',
      'filter_archived': 'Archivés',
      'filter_archived_single': 'Archivé',

      // ── Purchase Orders ──
      'order_title': 'Bons de Commande',
      'order_no_orders': 'Aucun bon de commande',
      'order_status_draft': 'Brouillon',
      'order_status_confirmed': 'Confirmée',
      'order_status_partial': 'Partiellement reçue',
      'order_status_received': 'Reçue',
      'order_status_cancelled': 'Annulée',
      'order_confirm': 'Confirmer',
      'order_confirm_confirm': 'Confirmer {order} ?',
      'order_receive': 'Recevoir le stock',
      'order_receive_title': 'Réception de stock',
      'order_receive_confirm': 'Valider la réception',
      'order_cancel_confirm': 'Annuler {order} ?',
      'order_items': 'articles',

      // ── Common form ──
      'yes': 'Oui',
      'no': 'Non',
      'form_edit': 'Modifier',
      'form_archive': 'Archiver',
      'form_reactivate': 'Réactiver',
      'form_product_edited': 'Produit modifié',
      'form_product_reactivated': 'Produit réactivé',
      'form_product_archived': 'Produit archivé',

      // ── Loyalty Points ──
      'pos_loyalty_points': 'Points fidélité',
      'pos_redeem_points': 'Utiliser points',
      'pos_points_balance': 'Points: {points}',
      'pos_redeem_title': 'Échanger des points',
      'pos_redeem_hint': 'Nombre de points (100 pts = 1 DA)',
      'pos_redeem_confirm': 'Échanger',
      'pos_redeem_success': 'Points échangés: {points} pts = {amount} DA de réduction',
      'pos_redeem_insufficient': 'Points insuffisants. Vous avez {points} pts',
      'pos_redeem_error': 'Erreur lors de l\'échange',

      // ── Customer Type ──
      'pos_customer_type_wholesale': 'GROS',
      'pos_customer_type_retail': 'DÉTAIL',
      'pos_wholesale_price': 'Prix gros',

      // ── Promotions ──
      'promo_title': 'Promotions',
      'promo_add': 'Nouvelle Promotion',
      'promo_edit': 'Modifier Promotion',
      'promo_name': 'Nom',
      'promo_discount_percent': 'Réduction %',
      'promo_start': 'Date début',
      'promo_end': 'Date fin',
      'promo_applies_to': 'Appliquer à',
      'promo_category': 'Catégorie',
      'promo_all': 'Tous les produits',
      'promo_active': 'Active',
      'promo_inactive': 'Inactive',
      'promo_no_promos': 'Aucune promotion',
      'promo_applied': 'Promotion appliquée : -{percent}%',
      'promo_save': 'Enregistrer',
      'promo_delete': 'Supprimer',
      'promo_saved': 'Promotion enregistrée',
      'promo_deleted': 'Promotion supprimée',

      // ── Inventory Adjustment ──
      'inv_adjust': 'Ajuster',
      'inv_adjust_title': 'Ajustement de stock',
      'inv_adjust_qty': 'Quantité (+/-)',
      'inv_adjust_reason': 'Motif',
      'inv_reason_breakage': 'Casse',
      'inv_reason_theft': 'Vol',
      'inv_reason_counting': 'Erreur comptage',
      'inv_reason_other': 'Autre',
      'inv_adjust_confirm': 'Confirmer l\'ajustement',
      'inv_adjusted': 'Stock ajusté avec succès',

      // ── Stock Count ──
      'stock_count_title': 'Comptage Stock',
      'stock_count_new': 'Nouveau comptage',
      'stock_count_open': 'Ouvert',
      'stock_count_closed': 'Fermé',
      'stock_count_enter_qty': 'Saisir quantité réelle',
      'stock_count_expected': 'Attendu',
      'stock_count_actual': 'Réel',
      'stock_count_delta': 'Écart',
      'stock_count_close': 'Fermer le comptage',
      'stock_count_confirm_close': 'Fermer et mettre à jour le stock ?',
      'stock_count_closed_success': 'Comptage fermé, stock mis à jour',
      'stock_count_no_counts': 'Aucun comptage',

      // ── Product Bundles ──
      'bundle_title': 'Packages',
      'bundle_name': 'Nom du pack',
      'bundle_price': 'Prix du pack',
      'bundle_no_bundles': 'Aucun pack',
      'bundle_added': 'Pack ajouté au panier',

      // ── Size Analytics ──
      'size_analytics_title': 'Analyse par taille',
      'size_label': 'Taille',
      'size_sold': 'Vendus',
      'size_revenue': 'Revenu',
      'size_pct': '%',
      'size_run_title': 'Gestion des tailles',
      'size_run_select_product': 'Sélectionnez un produit',
      'size_run_default_color': 'Par défaut',
      'product_color': 'Couleur',

      // ── Inventory Turnover ──
      'turnover_title': 'Rotation Stock',
      'turnover_fast': 'Rotation rapide',
      'turnover_slow': 'Rotation lente',
      'turnover_rate': 'Taux',
      'turnover_sold_30d': 'Vendus 30j',
      'turnover_current': 'Stock actuel',

      // ── Sales Forecast ──
      'forecast_title': 'Prévisions ventes',
      'forecast_month': 'Mois',
      'forecast_revenue': 'Revenu prévu',
      'forecast_next_3': '3 prochains mois',

      // ── Stock Transfers ──
      'transfer_title': 'Transferts Stock',
      'transfer_new': 'Nouveau transfert',
      'transfer_from': 'De',
      'transfer_to': 'Vers',
      'transfer_qty': 'Quantité',
      'transfer_variant': 'Variante',
      'transfer_status_pending': 'En attente',
      'transfer_status_done': 'Effectué',
      'transfer_execute': 'Exécuter',
      'transfer_execute_confirm': 'Confirmer le transfert ?',
      'transfer_done': 'Transfert effectué avec succès',
      'transfer_no_transfers': 'Aucun transfert',

      // ── Notifications ──
      'notif_title': 'Notifications',
      'notif_mark_all_read': 'Tout marquer lu',
      'notif_no_notifications': 'Aucune notification',

      // ── Missing keys (added) ──
      'label_invoice': 'Facture',
      'label_paid_badge': 'Payé',
      'nav_my_sales': 'Mes Ventes',
      'label_guest': 'Invité',
      'label_role_employee': 'Employé',
      'pos_today_total': "Total d'aujourd'hui",
      'pos_inv_col_num': 'N° Facture',
      'pos_inv_col_time': 'Heure',
      'pos_inv_col_total': 'Total',
    },

    // ────────────────────────────────────────────────────────────
    // ARABIC
    // ────────────────────────────────────────────────────────────
    'ar': {
      // ── Navigation ──
      'nav_dashboard': 'لوحة التحكم',
      'nav_products': 'المنتجات',
      'nav_add_product': 'إضافة منتج',
      'nav_inventory': 'المخزون',
      'nav_size_runs': 'المقاسات',
      'nav_sales': 'سجل المبيعات',
      'nav_clients': 'العملاء',
      'nav_suppliers': 'الموردون',
      'nav_employees': 'الموظفون',
      'nav_stores': 'المتاجر',
      'nav_pos': 'نقطة البيع',
      'nav_shifts': 'إدارة الوردية',
      'nav_activity': 'سجل النشاطات',
      'nav_expenses': 'المصاريف',
      'nav_recovery': 'تحصيل الديون',
      'nav_settings': 'الإعدادات',
      'nav_purchases': 'مشتريات الموردين',

      // ── Common actions ──
      'action_save': 'حفظ',
      'action_cancel': 'إلغاء',
      'action_delete': 'حذف',
      'action_confirm': 'تأكيد',
      'action_close': 'إغلاق',
      'action_refresh': 'تحديث',
      'action_add': 'إضافة',
      'action_edit': 'تعديل',
      'action_archive': 'أرشفة',
      'action_search': 'بحث',
      'action_filter': 'تصفية',
      'action_print': 'طباعة',
      'action_export': 'تصدير',
      'action_restore': 'استعادة',
      'action_confirm_delete': 'تأكيد الحذف',
      'action_add_to_list': 'إضافة للقائمة',

      // ── Common labels ──
      'label_name': 'الاسم',
      'label_phone': 'الهاتف',
      'label_email': 'البريد الإلكتروني',
      'label_address': 'العنوان',
      'label_amount': 'المبلغ',
      'label_date': 'التاريخ',
      'label_notes': 'ملاحظات',
      'label_status': 'الحالة',
      'label_store': 'المتجر',
      'label_balance': 'الرصيد',
      'label_total': 'الإجمالي:',
      'label_quantity': 'الكمية',
      'label_price': 'السعر',
      'label_description': 'الوصف',
      'label_category': 'التصنيف',
      'label_method': 'طريقة الدفع',
      'label_cash': 'نقداً',
      'label_bank': 'تحويل بنكي',
      'label_mobile': 'جوال',
      'label_active': 'نشط',
      'label_archived': 'مؤرشف',
      'label_all': 'الكل',
      'label_role': 'الدور',
      'label_role_admin': 'المدير',
      'label_password': 'كلمة المرور',
      'label_supplier': 'المورد',
      'label_product': 'المنتج',
      'label_stock': 'المخزون',
      'label_actions': 'إجراءات',
      'label_unit_price': 'سعر الوحدة',
      'label_qty_short': 'الكمية:',
      'label_phone_short': 'هاتف: ',
      'label_added_on': 'أضيف في :',

      // ── Auth ──
      'auth_title': 'تسجيل الدخول',
      'auth_email': 'البريد الإلكتروني',
      'auth_password': 'كلمة المرور',
      'auth_login': 'دخول',
      'auth_logout': 'تسجيل الخروج',
      'logout_confirm_msg': 'هل تريد تسجيل الخروج حقاً؟',
      'auth_error_invalid': 'البريد أو كلمة المرور غير صحيحة.',
      'auth_connecting': 'جاري الاتصال...',
      'auth_welcome': 'مرحباً',
      'auth_subtitle': 'نظام إدارة المخزون',
      'auth_forgot_password': 'نسيت كلمة المرور؟',
      'auth_access_denied_mobile': 'غير مسموح: التطبيق المحمول مخصص للمالك فقط.',
      'auth_profile_not_found': 'الملف الشخصي غير موجود. اتصل بالمسؤول.',
      'auth_connection_error': 'خطأ في الاتصال: تعذر التحقق من الملف الشخصي. تحقق من الإنترنت.',
      'auth_error_email': 'البريد الإلكتروني غير صالح.',
      'auth_fill_fields': 'الرجاء ملء جميع الحقول.',
      'pin_enter_title': 'أدخل رمز PIN',
      'pin_setup_title': 'تعيين رمز PIN (4 أرقام)',
      'pin_confirm_title': 'تأكيد رمز PIN',
      'pin_auth_biometric_reason': 'تحقق من هويتك لفتح القفل',
      'pin_setup_biometric': 'تفعيل البصمة؟',
      'pin_mismatch': 'الرموز غير متطابقة',
      'pin_incorrect': 'رمز PIN غير صحيح',
      'auth_error_generic': 'حدث خطأ غير متوقع.',
      'auth_welcome_msg': 'مرحباً، سجل الدخول للمتابعة',
      'auth_no_account': 'ليس لديك حساب؟ ',
      'auth_register_here': 'سجل هنا',

      // ── POS ──
      'pos_checkout': 'الدفع',
      'pos_add_to_cart': 'أضف إلى العربة',
      'pos_total': 'المبلغ الإجمالي :',
      'pos_walk_in_customer': 'زبون عابر',
      'pos_scanner_active': 'الماسح نشط',
      'pos_no_shift_warning': 'لا توجد وردية مفتوحة',
      'pos_debt_note': 'سيُضاف المتبقي إلى ديون العميل.',
      'pos_walk_in_note': 'زبون عابر: الدفع الكامل مطلوب (لا يمكن البيع بالدين).',
      'pos_enter_valid_price': 'الرجاء إدخال سعر صالح لكل منتج.',
      'pos_select_store': 'الرجاء اختيار المتجر.',
      'pos_stock_empty': 'تنبيه: المخزون نفد في هذا المتجر.',
      'pos_no_product': 'لم يتم العثور على منتج',
      'pos_paid_status': 'مدفوع',
      'pos_no_invoice_today': 'لا توجد فواتير مسجلة اليوم.',
      'pos_store_not_selected': 'لم يتم اختيار المتجر',
      'pos_report': 'التقرير',
      'pos_size': 'المقاس',
      'pos_color': 'اللون',
      'pos_code': 'الكود',
      'pos_payment_notes': 'دفع في نقطة البيع للفاتورة',
      'pos_unit_price': 'سعر الوحدة',
      'pos_system_error': 'خطأ في النظام',
      'pos_cart_title': 'العربة',
      'pos_items': 'عناصر',
      'pos_title': 'نقطة البيع (POS)',
      'pos_new_sale': 'بيع جديد',
      'pos_today_invoices': 'فواتير اليوم',
      'pos_report_btn': 'تقرير اليوم',
      'pos_search_hint': 'ابحث عن منتج أو امسح الباركود...',
      'pos_no_products': 'لم يتم العثور على منتجات',
      'pos_add_btn': 'إضافة',
      'pos_cart_empty': 'العربة فارغة',
      'pos_qty_short': 'الكمية: ',
      'pos_client_optional': 'عميل (اختياري)',
      'pos_walkin_client': 'عميل عابر',
      'pos_total_to_pay': 'الإجمالي المطلوب دفعه',
      'pos_pay_btn': 'دفع',
      'pos_no_store_selected': 'لم يتم اختيار متجر.',
      'pos_no_today_invoices': 'لا توجد فواتير مسجلة اليوم.',
      'pos_invoice': 'فاتورة:',
      'pos_client': 'عميل:',
      'pos_time': 'الوقت:',
      'pos_status': 'الحالة:',
      'pos_credit_unpaid': 'دَين (غير مسدد)',
      'pos_paid': 'مدفوع',
      'pos_remaining': 'المتبقي:',
      'pos_cashout_title': 'استلام الدفع',
      'pos_total_to_pay_lbl': 'الإجمالي المطلوب دفعه :',
      'pos_walkin_warning': 'عميل عابر: يجب دفع المبلغ كاملاً (لا يمكن البيع بالدين).',
      'pos_amount_received': 'المبلغ المستلم',
      'pos_credit_note': 'سيتم إضافة الباقي إلى ديون العميل.',
      'pos_validate_sale': 'تأكيد البيع',
      'pos_select_store_first': 'الرجاء اختيار متجر أولاً.',
      'pos_stock_empty_warning': 'تنبيه: نفد المخزون في هذا المتجر.',
      'pos_stock_insufficient': 'مخزون غير كافٍ — فقط',
      'pos_stock_available': 'متوفر',
      'pos_out_of_stock': 'نفد المخزون',
      'pos_stock_badge': 'المخزون:',
      'pos_item_oos': 'لم يعد متوفراً بالمخزون',
      'pos_invalid_price': 'الرجاء إدخال سعر صحيح لكل عنصر.',
      'pos_sale_success': 'تم تسجيل البيع! تم تحديث الفاتورة والمخزون.',
      'pos_access_denied': 'وصول مرفوض: صلاحيات غير كافية',
      'pos_payment_method': 'طريقة الدفع',
      'pos_cash': 'نقداً',
      'pos_credit': 'دين',
      'pos_mixed': 'مختلط',
      'pos_client_balance_current': 'الرصيد الحالي للعميل:',
      'pos_balance_new_warning': 'الرصيد الجديد بعد البيع:',
      'pos_cash_amount': 'المبلغ النقدي',
      'pos_credit_amount': 'مبلغ الدين',
      'pos_credit_client_only': 'الدين مخصص للعملاء المسجلين فقط',
      'pos_stock_changed_title': 'تغير المخزون',
      'pos_stock_changed_msg': 'تغير مخزون بعض الأصناف. تم تعديل الكميات.',
      'pos_inv_search_hint': 'ابحث عن عميل أو رقم فاتورة...',
      'pos_inv_filter_all': 'الكل',
      'pos_inv_filter_paid': 'مدفوع',
      'pos_inv_filter_credit': 'دين',
      'pos_inv_page_prev': 'السابق',
      'pos_inv_page_next': 'التالي',
      'pos_inv_page_of': 'الصفحة {current} / {total}',
      'pos_inv_articles': 'المواد:',
      'pos_inv_discount': 'الخصم:',
      'pos_inv_paid_label': 'المدفوع:',
      'pos_inv_remaining_label': 'المتبقي:',
      'pos_inv_mode': 'طريقة الدفع:',
      'pos_inv_seller': 'البائع:',
      'pos_inv_reprint': 'إعادة طباعة التذكرة',
      'pos_inv_print_pending': 'الطباعة قيد التطوير',
      'pos_inv_no_items': 'لا توجد مواد',
      'pos_inv_credit_status': 'دين',
      'pos_discount_percent': '%',
      'pos_discount_fixed': 'د.ج',
      'pos_discount_apply': 'تطبيق',
      'pos_discount_subtotal': 'المجموع',
      'pos_discount_remise_lbl': 'الخصم',
      'pos_discount_exceeds': 'الخصم يتجاوز الحد الأقصى المسموح به ({max}%)',
      'pos_discount_limit': 'حد الخصم',
      'pos_discount_apply_max': 'تطبيق الحد الأقصى',
      'pos_credit_limit': 'حد الائتمان:',
      'pos_credit_limit_exceeded': 'مبلغ الائتمان يتجاوز الحد المسموح! الرصيد: {balance}, الحد: {limit}',
      'pos_customer_balance': 'الرصيد:',
      'pos_customer_credit_limit': 'الحد:',
      'store_max_discount': 'أقصى خصم (%)',
      'pos_cart_clear': 'إفراغ',
      'pos_cart_clear_confirm': 'إفراغ العربة؟',
      'pos_cart_clear_yes': 'نعم، إفراغ',
      'pos_cart_clear_no': 'إلغاء',
      'pos_print_title': 'طباعة التذاكر',
      'pos_print_ask': 'هل تريد طباعة تذكرة تلقائياً بعد كل عملية بيع اليوم؟',
      'pos_print_always': 'نعم، طباعة دائمة',
      'pos_print_manual': 'لا، اسأل في كل مرة',
      'pos_print_auto_label': 'تلقائي',
      'pos_print_manual_label': 'يدوي',
      'pos_print_auto_msg': 'تم إرسال التذكرة للطباعة',
      'pos_print_now': 'طباعة التذكرة',
      'pos_print_ignore': 'تجاهل',
      'pos_change_label': 'الباقي:',
      'pos_insufficient': 'المبلغ غير كافٍ',
      'pos_confirm_payment': 'تأكيد البيع',
      'pos_price_label': 'السعر',
      'pos_new_price_label': 'السعر الجديد',
      'pos_online_status': 'متصل',
      'pos_offline_status': 'غير متصل',
      'pos_pending_ops': 'عملية (عمليات) معلقة',
      'pos_error': 'خطأ:',
      'pos_refund_btn': 'إرجاع البيع',
      'pos_return_resell_btn': 'إرجاع + إعادة بيع',
      'pos_refund_title': 'إرجاع المبيعة',
      'pos_refund_warning': 'هذا الإجراء لا يمكن التراجع عنه. سيُعاد المخزون وتُلغى الفاتورة.',
      'pos_refund_select_items': 'اختر الأصناف المرتجعة:',
      'pos_refund_total': 'المبلغ المسترجع:',
      'pos_refund_reason': 'سبب الإرجاع',
      'pos_refund_reason_hint': 'مثال: منتج معيب...',
      'pos_refund_confirm': 'تأكيد الإرجاع',
      'pos_refund_success': 'تم الإرجاع بنجاح',
      'pos_print_auto_short': '🖨️ تلقائي',
      'pos_print_manual_short': '🖨️ يدوي',

      // ── Shifts ──
      'shift_open_title': 'فتح الوردية',
      'shift_close_title': 'إغلاق الوردية',
      'shift_opening_amount': 'المبلغ الابتدائي (د.ج)',
      'shift_closing_amount': 'المبلغ الفعلي في الصندوق',
      'shift_actual_amount': 'المبلغ الفعلي في الصندوق',
      'shift_report_title': 'تقرير اليوم',
      'shift_surplus': 'فائض',
      'shift_shortage': 'عجز',
      'shift_no_shift': 'يوم بدون وردية',
      'shift_open_success': 'تم فتح الوردية بنجاح',
      'shift_close_success': 'تم إغلاق الوردية',
      'shift_previous_unclosed': 'وردية غير مغلقة',
      'shift_previous_unclosed_msg': 'هناك وردية من تاريخ {date} لم يتم إغلاقها.',
      'shift_ignore': 'تجاهل',
      'shift_close_old': 'إغلاق القديمة',
      'shift_skip': 'بدون وردية',
      'shift_open': 'فتح الوردية',
      'shift_enter_amount': 'الرجاء إدخال المبلغ',
      'shift_invalid_amount': 'مبلغ غير صحيح',
      'shift_open_error': 'حدث خطأ أثناء فتح الوردية',
      'shift_retrieve_error': 'خطأ في استرجاع الوردية',
      'shift_instructions': 'أدخل المبلغ الموجود في الصندوق لبدء يوم العمل',
      'shift_initial_amount': 'المبلغ الابتدائي',
      'shift_total_sales': 'مجموع المبيعات',
      'shift_expected_amount': 'المبلغ المتوقع',
      'shift_notes': 'ملاحظات (اختياري)',
      'shift_close': 'إغلاق',
      'shift_close_dialog': 'إغلاق',
      'shift_no_shift_text': 'يوم بدون وردية',
      'shift_no_shift_desc': 'لا توجد وردية مفتوحة اليوم',

      // ── Products ──
      'prod_name': 'اسم المنتج',
      'prod_barcode': 'الباركود',
      'prod_size': 'المقاس',
      'prod_color': 'اللون',
      'prod_stock': 'المخزون',
      'prod_add_variant': 'إضافة صنف',
      'prod_edit_variant': 'تعديل صنف',
      'prod_archive_variant': 'أرشفة هذا الصنف',
      'prod_variant_updated': 'تم تحديث الصنف بنجاح.',
      'prod_title': 'إدارة المنتجات',
      'prod_list': 'قائمة المنتجات',
      'prod_add': 'إضافة منتج',
      'prod_add_title': 'إضافة منتج جديد',
      'prod_desc': 'الوصف',
      'prod_saved': 'تم حفظ المنتج بنجاح.',
      'prod_catalog_title': 'كتالوج المنتجات',
      'prod_add_btn': 'إضافة منتج',
      'prod_search_hint': 'ابحث عن منتج أو مورد...',
      'prod_active_count': 'المنتجات النشطة',
      'prod_no_results': 'لم يتم العثور على منتجات',
      'prod_no_supplier': 'بدون مورد',
      'prod_variants_count': 'أصناف',
      'prod_stock_label': 'المخزون: ',
      'prod_no_active_variants': 'لا توجد متغيرات نشطة.',
      'prod_details': 'التفاصيل',
      'prod_buy_sell_margin': 'شراء / بيع (هامش)',
      'prod_out_of_stock': 'غير متوفر',
      'prod_edit_price_code': 'تعديل السعر/الكود',
      'prod_archive_variant_title': 'أرشفة هذا المتغير؟',
      'prod_archive_variant_msg': 'لن يكون متاحًا للبيع بعد الآن، ولكنه سيبقى في الفواتير القديمة.',
      'prod_archive_title': 'أرشفة كل المنتج؟',
      'prod_archive_msg': 'سيتم إخفاء المنتج وجميع متغيراته من الكتالوج.',
      'prod_archive_btn': 'أرشفة المنتج',
      'prod_buy_short': 'ش: ',
      'prod_sell_short': 'ب: ',
      'prod_margin_short': 'هامش: +',
      'prod_add_variant_btn': 'إضافة صنف جديد',
      'prod_remove_variant': 'حذف الصنف',
      'prod_add_product_success': 'تمت إضافة المنتج بنجاح!',
      'prod_total_stock': 'المخزون الكلي',
      'prod_no_permission': 'ليس لديك صلاحية لإضافة منتجات',
      'prod_buy_price_hidden': '---',

      // ── Inventory ──
      'inv_title': 'المخزون',
      'inv_search_hint': 'البحث عن منتج (الاسم، الباركود، المقاس، اللون)...',
      'inv_filter_store': 'تصفية حسب المتجر',
      'inv_total_stock': 'إجمالي المخزون',
      'inv_total_value': 'القيمة الإجمالية',
      'inv_no_results': 'لم يتم العثور على منتجات.',
      'inv_all_stores': 'جميع المتاجر',
      'inv_low_stock': 'المخزون المنخفض فقط',
      'inv_transfer': 'نقل المخزون',
      'inv_variant_details': 'تفاصيل الصنف',
      'inv_summary': 'ملخص',
      'inv_products': 'منتجات',
      'inv_value': 'القيمة',
      'inv_dashboard_title': 'لوحة القيادة: المخزون والتدفقات',
      'inv_no_store_msg': 'لا يوجد متجر. أضف متجرًا أولاً.',
      'inv_stat_total_products': 'إجمالي المنتجات',
      'inv_stat_total_stock': 'إجمالي المخزون',
      'inv_units': 'وحدات',
      'inv_stat_total_value': 'القيمة (شراء)',
      'inv_stat_low_stock': 'مخزون منخفض',
      'inv_no_products': 'لا توجد منتجات في هذا المتجر',
      'inv_low_stock_alerts': 'تنبيهات المخزون المنخفض (< 3)',
      'inv_no_alerts': 'لا توجد تنبيهات. المخزون جيد!',
      'inv_recent_movements': 'أحدث التدفقات (وارد / صادر)',
      'inv_no_movements': 'لا توجد حركات حديثة',
      'inv_mov_in': 'تم الشراء',
      'inv_mov_out': 'تم البيع',
      'inv_read_only': 'عرض المخزون — للاطلاع فقط',

      // ── Misc ──
      'misc_by': 'بواسطة',
      'misc_system': 'النظام',
      'misc_currency': 'د.ج',
      'misc_no_results': 'لا توجد نتائج.',
      'misc_loading': 'جاري التحميل...',
      'misc_select_store': 'اختر متجراً',
      'misc_not_available': 'غ/م',
      'misc_unknown': 'غير معروف',
      'misc_online_only': 'متاح فقط عبر الإنترنت',
      'misc_end_of_list': 'نهاية القائمة',
      'misc_walk_in': 'زبون عابر',
      'misc_no_phone': 'بدون هاتف',
      'misc_no_email': 'بدون بريد',
      'misc_no_store': 'بدون متجر',
      'inv_mov_return': 'مرتجع',
      'action_load_more': 'تحميل المزيد',

      // ── Purchases ──
      'buy_title': 'شراء / تموين',
      'buy_qty_invalid': 'يجب أن تكون الكمية أكبر من 0.',
      'buy_fill_fields': 'الرجاء ملء جميع الحقول وإضافة عناصر.',
      'buy_validation_title': 'التأكيد والدفع',
      'buy_total_invoice': 'إجمالي الفاتورة :',
      'buy_amount_paid': 'المبلغ المدفوع للمورد',
      'buy_payment_note': 'ملاحظة: إذا دفعت أقل من الإجمالي، سيتم إضافة الباقي تلقائياً إلى ديون المورد.',
      'buy_confirm': 'تأكيد الشراء',
      'buy_success': 'تم تسجيل الفاتورة! تم تحديث المخزون والحسابات تلقائياً.',
      'buy_add_items': 'إضافة عناصر',
      'buy_store_receiving': 'متجر الاستلام',
      'buy_my_store': 'متجري',
      'buy_product_variant': 'المنتج (الصنف)',
      'buy_no_permission': 'ليس لديك صلاحية لتسجيل أوامر الشراء',
      'buy_read_only': 'عرض للاطلاع فقط — لا يمكنك تسجيل مشتريات',
      'buy_receipt': 'وصل الشراء',
      'buy_items': 'عناصر',
      'buy_no_items': 'لم يتم إضافة أي عناصر.',
      'buy_validate_pay': 'تأكيد ودفع',

      // ── Customers ──
      'cust_title': 'إدارة العملاء',
      'cust_title_full': 'إدارة العملاء والديون',
      'cust_search_hint': 'البحث عن عميل...',
      'cust_add': 'عميل جديد',
      'cust_add_tooltip': 'إضافة عميل',
      'cust_edit': 'تعديل العميل',
      'cust_full_name': 'الاسم الكامل',
      'cust_phone': 'الهاتف',
      'cust_email': 'البريد الإلكتروني',
      'cust_address': 'العنوان',
      'cust_balance': 'الرصيد',
      'cust_receive_payment': 'استلام دفعة',
      'cust_payment_recorded': 'تم تسجيل الدفعة بنجاح.',
      'cust_archived': 'تم أرشفة العميل.',
      'cust_restored': 'تم استعادة العميل.',
      'cust_tabs_info': 'معلومات',
      'cust_tabs_invoices': 'الفواتير',
      'cust_tabs_payments': 'المدفوعات',
      'cust_no_client_selected': 'اختر عميلاً لعرض التفاصيل',
      'cust_payment_amount': 'المبلغ المستلم',
      'cust_payment_notes': 'ملاحظات / السبب',
      'cust_no_results': 'لم يتم العثور على عملاء.',
      'cust_active': 'نشطون',
      'cust_inactive': 'مؤرشفون',
      'cust_debt': 'الدين',
      'cust_updated': 'تم تعديل العميل.',
      'cust_added': 'تمت إضافة العميل.',
      'cust_archive_title': 'أرشفة العميل',
      'cust_archive_msg': 'هل تريد إخفاء هذا العميل؟ (سيتم الاحتفاظ بفواتيره).',
      'cust_manual_payment': 'دفعة يدوية (عميل)',
      'cust_with_debt': 'المدينون',
      'cust_register_payment_btn': 'تسجيل دفعة',
      'cust_no_purchases': 'لا توجد مشتريات مسجلة.',
      'cust_payment_of': 'دفعة بقيمة',

      // ── Suppliers ──
      'supp_title': 'إدارة الموردين',
      'supp_search_hint': 'البحث عن مورد...',
      'supp_add': 'مورد جديد',
      'supp_company': 'اسم الشركة',
      'supp_contact': 'اسم جهة الاتصال',
      'supp_balance': 'الرصيد',
      'supp_payment_recorded': 'تم تسجيل الدفعة.',
      'supp_archived': 'تم أرشفة المورد.',
      'supp_tabs_info': 'معلومات',
      'supp_tabs_purchases': 'المشتريات',
      'supp_tabs_payments': 'الدفعات',
      'supp_payment_amount': 'المبلغ المدفوع',
      'supp_payment_notes': 'ملاحظات / السبب',
      'supp_no_results': 'لم يتم العثور على موردين.',
      'supp_no_selected': 'اختر مورداً لعرض التفاصيل',
      'supp_active': 'نشطون',
      'supp_inactive': 'مؤرشفون',
      'supp_with_debt': 'المدينون فقط',
      'supp_edit': 'تعديل المورد',
      'supp_archive_title': 'أرشفة المورد',
      'supp_archive_msg': 'هل تريد إخفاء هذا المورد؟ (سيتم الاحتفاظ بفواتيره القديمة).',
      'supp_no_debt': 'لا يوجد موردون مدينون.',
      'supp_contact_prefix': 'جهة الاتصال: ',
      'supp_debt_credit': 'ديون (رصيد)',
      'supp_new_payment': 'دفعة جديدة',
      'supp_current_debt': 'الدين الحالي: ',
      'supp_manual_payment': 'دفعة يدوية',
      'supp_make_payment': 'تسجيل دفعة',
      'supp_no_invoices': 'لا توجد فواتير شراء لهذا المورد.',
      'supp_no_payments': 'لا توجد دفعات مسجلة.',
      'supp_payment_of': 'دفعة بقيمة ',
      'supp_reason': 'السبب: ',
      'supp_compare': 'مقارنة',

      // ── Supplier Comparison ──
      'comparison_select_product': 'اختيار منتج',
      'comparison_search_hint': 'البحث بالاسم أو الرمز الشريطي...',
      'comparison_no_variants': 'لم يتم العثور على منتجات',
      'comparison_title': 'مقارنة',
      'comparison_no_data': 'لا توجد بيانات مقارنة لهذا المنتج',
      'comparison_supplier': 'المورد',
      'comparison_last_price': 'آخر سعر',
      'comparison_avg_price': 'متوسط السعر',
      'comparison_min_price': 'الأدنى',
      'comparison_max_price': 'الأعلى',
      'comparison_purchases': 'المشتريات',

      // ── Employees ──
      'emp_title': 'إدارة الموظفين',
      'emp_add': 'إضافة موظف',
      'emp_add_btn': 'إنشاء الموظف',
      'emp_edit': 'تعديل الموظف',
      'emp_edit_btn': 'حفظ التعديلات',
      'emp_delete': 'حذف',
      'emp_assign_store': 'تعيين في متجر',
      'emp_created': 'تم إنشاء الموظف بنجاح!',
      'emp_updated': 'تم تعديل الموظف بنجاح.',
      'emp_deleted': 'تم حذف الموظف بنجاح.',
      'emp_suspended': 'تم تعليق الموظف بنجاح.',
      'emp_reactivated': 'تم إعادة تنشيط الموظف بنجاح.',
      'emp_archived': 'تم أرشفة الموظف نهائياً.',
      'emp_name': 'الاسم الكامل',
      'emp_first_name': 'الاسم الأول',
      'emp_last_name': 'اسم العائلة',
      'emp_email': 'البريد الإلكتروني',
      'emp_password': 'كلمة المرور',
      'emp_password_optional': 'اتركه فارغاً إذا لم ترد التغيير',
      'emp_phone': 'الهاتف',
      'emp_address': 'العنوان',
      'emp_job_title': 'المسمى الوظيفي',
      'emp_hired_at': 'تاريخ التوظيف',
      'emp_since_date': 'منذ',
      'emp_work_duration': 'مدة العمل',
      'emp_confirm_delete': 'تأكيد الحذف',
      'emp_delete_confirm_msg': 'هل تريد حقاً حذف هذا الموظف؟\n\nهذا الإجراء لا رجعة فيه وسيتم حذف حسابه.',
      'emp_delete_warning': 'هذا الإجراء لا رجعة فيه.',
      'emp_confirm_suspend': 'تعليق الموظف؟',
      'emp_confirm_suspend_msg': 'لن يتمكن الموظف من تسجيل الدخول. يمكنك إعادة تنشيطه لاحقاً.',
      'emp_confirm_archive': 'أرشفة نهائية؟',
      'emp_confirm_archive_msg': 'هذا الإجراء لا رجعة فيه. سيتم إخفاء الموظف نهائياً من جميع القوائم.',
      'emp_list_title': 'قائمة الموظفين',
      'emp_no_permission': 'ليس لديك صلاحية لعرض قائمة الموظفين',
      'emp_no_results': 'لم يتم العثور على موظفين.',
      'emp_select_hint': 'اختر موظفاً لعرض التفاصيل',
      'emp_active_tab': 'نشطون',
      'emp_suspended_tab': 'موقوفون',
      'emp_archived_tab': 'مؤرشفون',
      'emp_suspend_btn': 'تعليق',
      'emp_reactivate_btn': 'إعادة تنشيط',
      'emp_archive_btn': 'أرشفة نهائية',
      'emp_status_active': 'نشط',
      'emp_status_suspended': 'موقوف',
      'emp_status_archived': 'مؤرشف',
      'emp_role_label': 'موظف',
      'emp_search_hint': 'البحث عن موظف...',

      // ── Stores ──
      'store_title': 'إدارة المتاجر',
      'store_add': 'متجر جديد',
      'store_name': 'اسم المتجر',
      'store_created': 'تم إنشاء المتجر بنجاح.',
      'store_no_results': 'لم يتم العثور على متاجر.',
      'store_edit': 'تعديل المتجر',
      'store_updated': 'تم تعديل المتجر بنجاح.',
      'store_delete_msg': 'هل تريد حذف المتجر \'{name}\'؟\n\nلن يتم حذف المتجر إلا إذا كان غير مرتبط بموظفين أو مخزون.',
      'store_deleted': 'تم حذف المتجر بنجاح.',
      'store_delete_error': 'لا يمكن حذف المتجر (قد يكون مرتبطاً ببيانات أخرى).',
      'store_no_results_yet': 'لا توجد متاجر حالياً',
      'store_add_first': 'أضف متجرك الأول للبدء',
      'store_add_btn': 'إضافة متجر',
      'store_employees': 'موظفين',
      'store_units': 'وحدات',

      // ── Expenses ──
      'exp_title': 'إدارة المصاريف',
      'exp_add': 'مصروف جديد',
      'exp_category': 'التصنيف',
      'exp_category_add': 'إضافة تصنيف',
      'exp_category_title': 'تصنيفات المصاريف',
      'exp_category_hint': 'اسم التصنيف',
      'exp_method': 'طريقة الدفع',
      'exp_month_total': 'إجمالي الشهر',
      'exp_count': 'العدد',
      'exp_max': 'الأكبر',
      'exp_recorded': 'تم تسجيل المصروف.',
      'exp_amount': 'المبلغ (د.ج)',
      'exp_date': 'تاريخ المصروف',
      'exp_change_date': 'تغيير',
      'exp_no_category': 'بدون تصنيف',
      'exp_no_results': 'لا توجد مصاريف مسجلة.',
      'exp_manage_categories': 'إدارة التصنيفات',
      'exp_period': 'الفترة',
      'exp_all_categories': 'الكل',
      'exp_expenses_label': 'مصاريف',

      // ── Debt Recovery ──
      'debt_title': 'تحصيل الديون',
      'debt_search_hint': 'البحث عن عميل...',
      'debt_total_debt': 'إجمالي الديون',
      'debt_receive_payment': 'استلام دفعة',
      'debt_payment_history': 'سجل المدفوعات',
      'debt_client_info': 'معلومات العميل',
      'debt_new_balance': 'الرصيد الجديد',
      'debt_recorded': 'تم تسجيل الدفعة بنجاح.',
      'debt_current_balance': 'الرصيد الحالي',
      'debt_amount_received': 'المبلغ المستلم (د.ج)',
      'debt_notes': 'ملاحظات (اختياري)',
      'debt_confirm_payment': 'تأكيد الدفع',
      'debt_no_debt': 'لا يوجد عملاء مدينون!',
      'debt_no_payments': 'لا توجد مدفوعات تحصيل.',
      'debt_clients_count': 'عملاء مدينون',
      'debt_select_client': 'اختر عميلاً لعرض التفاصيل',
      'debt_not_specified': 'غير محدد',
      'debt_overdue_clients': 'عملاء متأخرين في السداد',
      'debt_days_overdue': 'متأخر',
      'debt_days': 'أيام',

      // ── Dashboard ──
      'dash_title': 'لوحة التحكم',
      'dash_today_sales': 'مبيعات اليوم',
      'dash_month_sales': 'مبيعات الشهر',
      'dash_top_products': 'الأكثر مبيعاً',
      'dash_revenue': 'الإيرادات',
      'dash_expenses_month': 'مصاريف الشهر',
      'dash_net_profit': 'صافي الربح',
      'dash_last_month': 'الشهر الماضي',
      'dash_this_month': 'هذا الشهر',
      'dash_today': 'اليوم',
      'dash_stores_comparison': 'مقارنة المتاجر',
      'dash_welcome': 'مرحباً',
      'dash_overview': 'نظرة عامة',
      'dash_evolution': 'تطور المبيعات',
      'dash_7days': 'آخر 7 أيام',
      'dash_customer_debt': 'ديون العملاء',
      'dash_supplier_debt': 'ديون الموردين',
      'dash_total_profit': 'إجمالي الربح',
      'dash_avg_margin': 'متوسط الهامش',
      'dash_stock_value': 'قيمة المخزون',
      'dash_active_cust': 'العملاء النشطون',
      'dash_active_supp': 'الموردون النشطون',
      'dash_credits_in_progress': 'ديون قيد التحصيل',
      'dash_to_settle': 'ديون للموردين',
      'dash_day_mon': 'إث',
      'dash_day_tue': 'ثل',
      'dash_day_wed': 'أر',
      'dash_day_thu': 'خم',
      'dash_day_fri': 'جم',
      'dash_day_sat': 'سب',
      'dash_day_today': 'اليوم',
      // ── Dashboard (new) ──
      'dash_today_sales_count': 'فواتير اليوم',
      'dash_today_expenses': 'مصروفات اليوم',
      'dash_low_stock': 'مخزون منخفض',
      'dash_revenue_chart': 'تطور الإيرادات',
      'dash_period': 'الفترة',
      'dash_week': '7 أيام',
      'dash_3months': '90 يوماً',
      'dash_no_data': 'لا توجد بيانات',
      'dash_recent_activity': 'آخر النشاطات',
      'dash_no_activity': 'لا توجد نشاطات حديثة',
      'dash_ranking': 'الترتيب',
      'dash_product_name': 'المنتج',
      'dash_sold_qty': 'الكمية المباعة',
      'dash_total_revenue': 'الإيرادات',
      'dash_no_products_sold': 'لا توجد منتجات مباعة هذا الشهر',
      'dash_debt_clients': 'العملاء المدينون',
      'dash_no_debt_clients': 'لا يوجد عملاء مدينون',
      'dash_my_sales': 'مبيعاتي',
      'dash_my_sales_today': 'مبيعاتي اليوم',
      'dash_no_sales': 'لا توجد مبيعات مسجلة',
      'dash_sales_count': 'عدد المبيعات',
      'dash_item_count': 'عناصر',
      'dash_month': '30 يوماً',
      'dash_today_revenue': 'إيرادات اليوم',
      'dash_employee_dashboard': 'لوحة تحكم الموظف',

      // ── Sales History ──
      'sales_title': 'سجل المبيعات',
      'sales_search': 'بحث',
      'sales_invoice': 'فاتورة',
      'sales_status_paid': 'مدفوع ✓',
      'sales_status_partial': 'جزئي',
      'sales_status_unpaid': 'غير مدفوع',
      'sales_status_refunded': 'مُرجَع ↩',
      'sales_status_returned': 'مُعاد',
      'sales_status_cancelled': 'مُلغى',
      'sales_no_results': 'لم يتم العثور على مبيعات.',
      'sales_all_stores': 'جميع المتاجر',
      'sales_report': 'التقرير',
      'sales_customer': 'العميل',
      'sales_store': 'المتجر',
      'sales_refund': 'إرجاع',
      'sales_sold_by': 'تم البيع بواسطة',

      // ── Refund ──
      'refund_title': 'إرجاع المشتريات',
      'refund_select_items': 'حدد العناصر التي سيتم إرجاعها:',
      'refund_reason': 'سبب الإرجاع (اختياري)',
      'refund_confirm': 'تأكيد الإرجاع',
      'refund_success': 'تمت عملية الإرجاع بنجاح. معرف:',
      'refund_min_one_item': 'الرجاء تحديد عنصر واحد على الأقل للإرجاع',
      'refund_quantity': 'الكمية المرجعة:',
      'refund_original_invoice': 'الفاتورة الأصلية:',
      'refund_total_amount': 'إجمالي مبلغ الإرجاع:',
      'refund_unit_price': 'السعر:',
      'refund_48h_blocked': 'لا يمكن إرجاع فاتورة بعد 48 ساعة من البيع',
      'refund_48h_warning_title': 'تحذير: تجاوز المدة',
      'refund_48h_warning_body': 'تحذير: مضى على هذه الفاتورة أكثر من 48 ساعة. هل تريد المتابعة؟',
      'refund_48h_continue': 'متابعة الإرجاع',
      'refund_invoice_age': 'تم البيع منذ {hours} ساعة',

      // ── Activity Logs ──
      'log_title': 'سجل النشاطات',
      'log_action': 'الإجراء',
      'log_user': 'المستخدم',
      'log_date': 'التاريخ',
      'log_no_results': 'لا توجد سجلات.',
      'label_performed_action': 'قام بـ',
      'label_date_from': 'من',
      'label_date_to': 'إلى',
      'log_filter_action': 'فلتر حسب العملية',
      'log_filter_date': 'فلتر حسب التاريخ',
      'log_load_more': 'تحميل المزيد',
      'log_no_more': 'لا توجد نتائج إضافية',
      'log_all_actions': 'كل العمليات',
      'log_reset_filters': 'إعادة تعيين الفلاتر',
      'log_results_count': 'نتيجة',
      'label_sale': 'بيع',
      'label_supply': 'شراء',
      'label_return': 'مرتجع',
      'label_create_employee': 'إنشاء موظف',
      'label_update_employee': 'تعديل موظف',
      'label_suspend_employee': 'تعطيل موظف',
      'label_reactivate_employee': 'إحياء موظف',
      'label_permanent_delete_employee': 'أرشفة موظف',
      'label_delete_employee': 'حذف موظف',
      'label_add_expense': 'مصروف',
      'label_add_debt_recovery': 'تحصيل دين',
      'label_remaining': 'متبقي',
      'label_refund': 'استرداد',

      // ── Messages success ──
      'msg_saved': 'تم الحفظ بنجاح.',
      'msg_deleted': 'تم الحذف بنجاح.',
      'msg_payment_recorded': 'تم تسجيل الدفعة بنجاح.',
      'msg_sale_recorded': 'تم تسجيل البيع بنجاح.',
      'msg_updated': 'تم التحديث بنجاح.',
      'msg_archived': 'تم الأرشفة بنجاح.',
      'msg_restored': 'تم الاستعادة بنجاح.',

      // ── Messages error ──
      'msg_error': 'خطأ',
      'msg_access_denied': 'تم رفض الوصول: صلاحيات غير كافية',
      'msg_invalid_amount': 'مبلغ غير صالح',
      'msg_required': 'مطلوب',
      'msg_load_error': 'خطأ في التحميل',
      'msg_connection_error': 'خطأ في الاتصال',
      'msg_invalid': 'غير صالح',
      'msg_min_4_chars': 'الحد الأدنى 4 أحرف.',

      // ── Offline ──
      'offline_mode': 'وضع عدم الاتصال',
      'offline_banner': 'أنت في وضع عدم الاتصال',
      'offline_pending': 'عمليات معلقة',
      'offline_sync': 'مزامنة',
      'offline_connected': 'وضع عدم الاتصال (متصل)',
      'offline_synced': 'تم المزامنة ✓',
      'offline_sync_now': 'مزامنة الآن',
      'online_mode': 'متصل',

      // ── Settings ──
      'settings_language': 'اللغة',
      'settings_ar': 'العربية',
      'settings_fr': 'Français',

      // ── Mode selection ──
      'mode_title': 'اختيار الوضع',
      'mode_online': 'متصل',
      'mode_online_desc': 'وصول مباشر (مُوصى به)',
      'mode_offline': 'غير متصل',
      'mode_offline_desc': 'العمل بدون إنترنت',
      'mode_seeding': 'تهيئة القاعدة المحلية...',
      'mode_syncing': 'جاري المزامنة الأولية...',
      'mode_ready': 'البيانات المحلية جاهزة ✓',
      'mode_no_store': 'خطأ: لا يوجد متجر مخصص.',

      // ── Purchases (supplier) ──
      'purchase_title': 'مشتريات الموردين',
      'purchase_add': 'شراء جديد',
      'purchase_amount_paid': 'المبلغ المدفوع للمورد',
      'purchase_supplier': 'المورد',
      'purchase_store': 'متجر الاستلام',
      'purchase_product': 'المنتج (الصنف)',
      'purchase_quantity': 'الكمية',
      'purchase_unit_price': 'سعر الشراء للوحدة',
      'purchase_no_results': 'لم يتم العثور على مشتريات.',

      // ── Owner dashboard (mobile) ──
      'owner_inventory': 'المخزون',
      'owner_analytics': 'التحليلات',
      'owner_profile': 'الملف الشخصي',
      'owner_new_password': 'كلمة مرور جديدة',
      'owner_confirm_password': 'تأكيد كلمة المرور',
      'owner_min_chars': 'الحد الأدنى 6 أحرف.',
      'owner_passwords_mismatch': 'كلمتا المرور غير متطابقتين.',
      'owner_password_changed': 'تم تغيير كلمة المرور بنجاح ✅',
      'owner_product_not_found': 'المنتج غير موجود.',
      'owner_change_password': 'تغيير كلمة المرور',
      'owner_scanner_title': 'الماسح (المالك)',
      'owner_buy_price': 'سعر الشراء:',
      'owner_sell_price': 'سعر البيع:',
      'owner_net_margin': 'الربح الصافي:',
      'owner_stocks_per_store': 'المخزون حسب المتجر:',
      'owner_dash_title': 'لوحة التحكم الرئيسية',
      'owner_financial_health': 'الوضع المالي (اليوم)',
      'owner_store_performance': 'أداء المتاجر',
      'owner_qty_remaining': 'متبقٍ',
      'owner_recent_activities': 'النشاطات الأخيرة',
      'owner_inv_all_stores': 'المخزون — جميع المتاجر',
      'owner_no_items_stock': 'لا يوجد منتجات في المخزون.',
      'owner_sales_section': 'المبيعات',
      'owner_vs_last_month': 'مقارنة بالشهر الماضي',
      'owner_top_5_products': 'أفضل 5 منتجات (هذا الشهر)',
      'owner_qty_sold': 'مباع',
      'owner_store_comp_today': 'مقارنة المتاجر (اليوم)',
      'auth_logout_confirm': 'هل تريد حقاً تسجيل الخروج؟',
      'owner_role_label': 'المالك',

      // ── Contact / WhatsApp / SMS ──
      'contact_whatsapp_msg': 'مرحباً {name}، رصيدكم المستحق {amount} DA متأخر لمدة {days} يوماً.',
      'contact_sms_msg': 'مرحباً {name}، رصيدكم المستحق: {amount}. نرجو التسوية في أقرب وقت. شكراً.',
      'contact_no_phone': 'لا يوجد رقم هاتف لهذا العميل',
      'contact_debt_list_title': 'العملاء المدينون',
      'contact_send_reminder': 'إرسال تذكير',
      'debt_whatsapp_reminder': 'تذكير واتساب',
      'debt_sms_reminder': 'تذكير SMS',

      // ── Dates ──
      'day_mon': 'الإثنين', 'day_tue': 'الثلاثاء', 'day_wed': 'الأربعاء', 'day_thu': 'الخميس', 'day_fri': 'الجمعة', 'day_sat': 'السبت', 'day_sun': 'الأحد',
      'month_1': 'جانفي', 'month_2': 'فيفري', 'month_3': 'مارس', 'month_4': 'أفريل', 'month_5': 'ماي', 'month_6': 'جوان',
      'month_7': 'جويلية', 'month_8': 'أوت', 'month_9': 'سبتمبر', 'month_10': 'أكتوبر', 'month_11': 'نوفمبر', 'month_12': 'ديسمبر',

      // ── Filters ──
      'filter_all': 'الكل',
      'filter_men': 'رجل',
      'filter_women': 'امرأة',
      'filter_kid': 'طفل',
      'filter_instock': 'متوفر',
      'filter_low_stock': 'منخفض',
      'filter_out_of_stock': 'نفد',
      'filter_active': 'نشطون',
      'filter_suspended': 'موقوفون',
      'filter_archived': 'مؤرشفون',
      'filter_archived_single': 'مؤرشف',

      // ── Purchase Orders ──
      'order_title': 'أوامر الشراء',
      'order_no_orders': 'لا توجد أوامر شراء',
      'order_status_draft': 'مسودة',
      'order_status_confirmed': 'مؤكدة',
      'order_status_partial': 'مستلمة جزئياً',
      'order_status_received': 'مستلمة',
      'order_status_cancelled': 'ملغاة',
      'order_confirm': 'تأكيد',
      'order_confirm_confirm': 'تأكيد {order} ؟',
      'order_receive': 'استلام المخزون',
      'order_receive_title': 'استلام مخزون',
      'order_receive_confirm': 'تأكيد الاستلام',
      'order_cancel_confirm': 'إلغاء {order} ؟',
      'order_items': 'عناصر',

      // ── Common form ──
      'yes': 'نعم',
      'no': 'لا',
      'form_edit': 'تعديل',
      'form_archive': 'أرشفة',
      'form_reactivate': 'إعادة تنشيط',
      'form_product_edited': 'تم تعديل المنتج',
      'form_product_reactivated': 'تم إعادة تنشيط المنتج',
      'form_product_archived': 'تم أرشفة المنتج',

      // ── Loyalty Points ──
      'pos_loyalty_points': 'نقاط الولاء',
      'pos_redeem_points': 'استخدام النقاط',
      'pos_points_balance': 'النقاط: {points}',
      'pos_redeem_title': 'استبدال النقاط',
      'pos_redeem_hint': 'عدد النقاط (100 نقطة = 1 د.ج)',
      'pos_redeem_confirm': 'استبدال',
      'pos_redeem_success': 'تم استبدال {points} نقطة = {amount} د.ج خصم',
      'pos_redeem_insufficient': 'نقاط غير كافية. لديك {points} نقطة',
      'pos_redeem_error': 'خطأ في الاستبدال',

      // ── Customer Type ──
      'pos_customer_type_wholesale': 'جملة',
      'pos_customer_type_retail': 'قطاعي',
      'pos_wholesale_price': 'سعر الجملة',

      // ── Promotions ──
      'promo_title': 'العروض',
      'promo_add': 'عرض جديد',
      'promo_edit': 'تعديل العرض',
      'promo_name': 'الاسم',
      'promo_discount_percent': 'نسبة الخصم %',
      'promo_start': 'تاريخ البداية',
      'promo_end': 'تاريخ النهاية',
      'promo_applies_to': 'يطبق على',
      'promo_category': 'الفئة',
      'promo_all': 'جميع المنتجات',
      'promo_active': 'نشط',
      'promo_inactive': 'غير نشط',
      'promo_no_promos': 'لا توجد عروض',
      'promo_applied': 'تم تطبيق العرض: -{percent}%',
      'promo_save': 'حفظ',
      'promo_delete': 'حذف',
      'promo_saved': 'تم حفظ العرض',
      'promo_deleted': 'تم حذف العرض',

      // ── Inventory Adjustment ──
      'inv_adjust': 'تعديل',
      'inv_adjust_title': 'تعديل المخزون',
      'inv_adjust_qty': 'الكمية (+/-)',
      'inv_adjust_reason': 'السبب',
      'inv_reason_breakage': 'كسر',
      'inv_reason_theft': 'سرقة',
      'inv_reason_counting': 'خطأ في العد',
      'inv_reason_other': 'أخرى',
      'inv_adjust_confirm': 'تأكيد التعديل',
      'inv_adjusted': 'تم تعديل المخزون بنجاح',

      // ── Stock Count ──
      'stock_count_title': 'جرد المخزون',
      'stock_count_new': 'جرد جديد',
      'stock_count_open': 'مفتوح',
      'stock_count_closed': 'مغلق',
      'stock_count_enter_qty': 'إدخال الكمية الفعلية',
      'stock_count_expected': 'متوقع',
      'stock_count_actual': 'فعلي',
      'stock_count_delta': 'الفرق',
      'stock_count_close': 'إغلاق الجرد',
      'stock_count_confirm_close': 'إغلاق وتحديث المخزون؟',
      'stock_count_closed_success': 'تم إغلاق الجرد وتحديث المخزون',
      'stock_count_no_counts': 'لا يوجد جرد',

      // ── Product Bundles ──
      'bundle_title': 'الباقات',
      'bundle_name': 'اسم الباقة',
      'bundle_price': 'سعر الباقة',
      'bundle_no_bundles': 'لا توجد باقات',
      'bundle_added': 'تمت إضافة الباقة للسلة',

      // ── Size Analytics ──
      'size_analytics_title': 'تحليل المقاسات',
      'size_label': 'المقاس',
      'size_sold': 'مباع',
      'size_revenue': 'الإيراد',
      'size_pct': '%',
      'size_run_title': 'إدارة المقاسات',
      'size_run_select_product': 'اختر منتجاً',
      'size_run_default_color': 'افتراضي',
      'product_color': 'اللون',

      // ── Inventory Turnover ──
      'turnover_title': 'دوران المخزون',
      'turnover_fast': 'دوران سريع',
      'turnover_slow': 'دوران بطيء',
      'turnover_rate': 'المعدل',
      'turnover_sold_30d': 'مباع 30 يوم',
      'turnover_current': 'المخزون الحالي',

      // ── Sales Forecast ──
      'forecast_title': 'توقعات المبيعات',
      'forecast_month': 'الشهر',
      'forecast_revenue': 'الإيراد المتوقع',
      'forecast_next_3': 'الأشهر الثلاثة القادمة',

      // ── Stock Transfers ──
      'transfer_title': 'تحويلات المخزون',
      'transfer_new': 'تحويل جديد',
      'transfer_from': 'من',
      'transfer_to': 'إلى',
      'transfer_qty': 'الكمية',
      'transfer_variant': 'النوع',
      'transfer_status_pending': 'قيد الانتظار',
      'transfer_status_done': 'تم',
      'transfer_execute': 'تنفيذ',
      'transfer_execute_confirm': 'تأكيد التحويل؟',
      'transfer_done': 'تم التحويل بنجاح',
      'transfer_no_transfers': 'لا توجد تحويلات',

      // ── Notifications ──
      'notif_title': 'الإشعارات',
      'notif_mark_all_read': 'تحديد الكل كمقروء',
      'notif_no_notifications': 'لا توجد إشعارات',

      // ── Missing keys (added) ──
      'label_invoice': 'الفاتورة',
      'label_paid_badge': 'مدفوع',
      'nav_my_sales': 'مبيعاتي',
      'label_guest': 'ضيف',
      'label_role_employee': 'موظف',
      'pos_today_total': 'إجمالي اليوم',
      'pos_inv_col_num': 'رقم الفاتورة',
      'pos_inv_col_time': 'الوقت',
      'pos_inv_col_total': 'الإجمالي',
    },
  };
}